#!/bin/bash
crystallizeDestdir="$1"
crystallizePrefix="$2"
crystallizeCapPrefix="$3"
crystallizeExecPrefix="$4"
crystallizeBindir="$5"
crystallizeDatarootdir="$6"
crystallizeDatadir="$7"
crystallizeSysconfdir="$8"
crystallizeSharedstatedir="$9"
if ! [ -n "$crystallizePrefix" ]; then
    if ! [ -n "$crystallizeCapPrefix" ]; then
        crystallizePrefix="$crystallizeDestdir"/usr/local
    else
        crystallizePrefix="$crystallizeCapPrefix"
    fi
fi
if ! [ -n "$crystallizeExecPrefix" ]; then
    crystallizeExecPrefix="$crystallizePrefix"
fi
if ! [ -n "$crystallizeBindir" ]; then
    crystallizeBindir="$crystallizeExecPrefix"/bin
fi
if ! [ -n "$crystallizeDatarootdir" ]; then
    crystallizeDatarootdir="$crystallizePrefix"/share
fi
if ! [ -n "$crystallizeDatadir" ]; then
    crystallizeDatadir="$crystallizeDatarootdir"
fi
if ! [ -n "$crystallizeSysconfdir" ]; then
    crystallizeSysconfdir="$crystallizePrefix"/etc
fi
if ! [ -n "$crystallizeSharedstatedir" ]; then
    crystallizeSharedstatedir="$crystallizePrefix"/var
fi
export crystallizeBindir
export crystallizeSharedstatedir
export crystallizeSysconfdir
crystallizeBindirEsc="$(perl -0777 -e 'print(quotemeta($ENV{crystallizeBindir}))')"
crystallizeSharedstatedirEsc="$(perl -0777 -e 'print(quotemeta($ENV{crystallizeSharedstatedirEsc}))')"
crystallizeSysconfdirEsc="$(perl -0777 -e 'print(quotemeta($ENV{crystallizeSysconfdirEsc}))')"
perl -0777 -p -i -e "s/\/usr\/local\/bin/$crystallizeBindirEsc/g" scripts/decrystallize
perl -0777 -p -i -e "s/\/usr\/local\/bin/$crystallizeBindirEsc/g" scripts/quickliquid
perl -0777 -p -i -e "s/\/usr\/local\/bin/$crystallizeBindirEsc/g" scripts/crystallize-rescue
perl -0777 -p -i -e "s/\/usr\/local\/bin/$crystallizeBindirEsc/g" scripts/crystallize-update
perl -0777 -p -i -e "s/\/usr\/local\/etc/$crystallizeSysconfdirEsc/g" scripts/crystallize-getconf
perl -0777 -p -i -e "s/\/usr\/local\/var/$crystallizeSharedstatedirEsc/g" support/crystallize.conf
mkdir -p "$crystallizeBindir"
chmod +x scripts/*
cp scripts/* "$crystallizeBindir"
cp support/crystallize.conf "$crystallizeSysconfdir"
mkdir -p "$crystallizeSharedstatedir"/crystallize
