#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup || exit 1

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

echo 1 "$1" 2 "$2" 3 "$3" 4 "$4" 5 "$5" 6 "$6" 7 "$7" 8 "$8" 9 "$9"
crystallizeDestdir="$1"
crystallizePrefix="$2"
crystallizeCapPrefix="$3"
crystallizeExecPrefix="$4"
crystallizeBindir="$5"
crystallizeDatarootdir="$6"
crystallizeDatadir="$7"
crystallizeSysconfdir="$8"
crystallizeSharedstatedir="$9"
if ! [[ -n "$crystallizePrefix" ]]; then
    if ! [[ -n "$crystallizeCapPrefix" ]]; then
        crystallizePrefix="$crystallizeDestdir"/usr/local
    else
        crystallizePrefix="$crystallizeCapPrefix"
    fi
fi
echo "crystallizePrefix: $crystallizePrefix"
if ! [[ -n "$crystallizeExecPrefix" ]]; then
    crystallizeExecPrefix="$crystallizePrefix"
fi
echo "crystallizeExecPrefix: $crystallizeExecPrefix"
if ! [[ -n "$crystallizeBindir" ]]; then
    crystallizeBindir="$crystallizeExecPrefix"/bin
fi
echo "crystallizeBindir: $crystallizeBindir"
if ! [[ -n "$crystallizeDatarootdir" ]]; then
    crystallizeDatarootdir="$crystallizePrefix"/share
fi
echo "crystallizeDatarootdir: $crystallizeDatarootdir"
if ! [[ -n "$crystallizeDatadir" ]]; then
    crystallizeDatadir="$crystallizeDatarootdir"
fi
echo "crystallizeDatadir: $crystallizeDatadir"
if ! [[ -n "$crystallizeSysconfdir" ]]; then
    crystallizeSysconfdir="$crystallizePrefix"/etc
fi
echo "crystallizeSysconfdir: $crystallizeSysconfdir"
if ! [[ -n "$crystallizeSharedstatedir" ]]; then
    crystallizeSharedstatedir="$crystallizePrefix"/var
fi
echo "crystallizeSharedstatedir: $crystallizeSharedstatedir"

crystallizeEmberdir="$crystallizePrefix"/Ember\ Library

ereplace "73FAB73B-EEE4-4992-8622-4F3FCEC9823A" "$(date-uuid)" support/crystallize.conf
ereplace "/usr/local/var" "$crystallizeSharedstatedir" support/crystallize.conf
ereplace "/Ember\ Library/" "$crystallizeEmberdir" support/crystallize.conf
ereplace "/usr/local/etc" "$crystallizeSysconfdir" scripts/crystallize-getconf
ereplace "/usr/local/etc" "$crystallizeSysconfdir" scripts/crystallize-logsession

mkdir -p "$crystallizeBindir"
chmod +x scripts/*
cp scripts/* "$crystallizeBindir/"
mkdir -p "$crystallizeSysconfdir"
cp -v support/crystallize.conf "$crystallizeSysconfdir/"
mkdir -p "$crystallizeSharedstatedir"/crystallize
