#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
set -x

fail() {
    printf '%b' '\033[1;31m' >&2
    echo "Please install the current version of ember-shared before installing crystallize."
    printf '%b' '\033[0m' >&2
    exit 1
}

if [[ "$OSTYPE" = darwin* ]]; then
    if ! type "greadlink"; then
        fail
    fi
    if ! type "ember_bash_setup"; then
        fail
    fi
    find scripts -type f -exec bash -c "source ember_bash_setup &> /dev/null; perl -0777 -p -i -e '\''s/readlink /greadlink /g'\'' \"\$0\"" {} \;
    find scripts -type f -exec bash -c "source ember_bash_setup &> /dev/null; perl -0777 -p -i -e '\''s/sort /gsort /g'\'' \"\$0\"" {} \;
    find scripts -type f -exec bash -c "source ember_bash_setup &> /dev/null; set -x; perl -0777 -p -i -e '\''s/du /gdu /g'\'' \"\$0\"" {} \;
    find scripts -type f -exec bash -c "source ember_bash_setup &> /dev/null; set -x; perl -0777 -p -i -e '\''s/du /gdu /g'\'' \"\$0\"" {} \;
fi
