#!/bin/bash
# biggify

# See crystallize for requirements.

#Usage: biggify <crystal-directory>

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

#Script should exit if any operation fails.
set -e

shopt -s extglob

decrystallize-pointer "$1"
