#!/bin/bash
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
crystalWorkdir=$(crystallize-getconf 'WorkDirectory')
streamId="biggify-stream-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
(
    cd "$crystalWorkdir"
    mkdir "$streamId"
    (
        cd "$streamId"
        sponge "$streamId.xz"
        tail -c +38 "$streamId.xz" | unxz --stdout - | tar -xf -
        biggify *.crystal --here &> /dev/null
        unxz --stdout biggify-stream-*.xz
    )
)
