#!/bin/bash
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
crystalWorkdir=$(crystallize-getconf 'WorkDirectory')
(
    cd "$crystalWorkdir"
    sponge "$streamId.xz"
    tail -c +37 "$streamId.xz" | unxz --stdout - | tar -xf -
    biggify --here "$streamId.crystal" &> /dev/null
)
