#!/bin/bash

set -e

action="$1"
name="$2"

if [[ "$(whoami)" != "root" ]]; then
    whoami > /tmp/rubberfsUser
fi
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
rubberfsUser="$(cat /tmp/rubberfsUser)"

set -e

if [ ! -n "$name" ]; then
    name="library"
fi

/sbin/modprobe zfs

case $action in
create)
    mkdir -p "/Wreathe/.Resources/RubberFS/$name/dev/"
    #4T doesn't work: "truncate: failed to truncate '/Wreathe/.Resources/RubberFS/library/dev/StorageBlockDevice1' at 4398046511104 bytes: File too large" — wtf?! I don't have 3tb available either.
    truncate -s 3T "/Wreathe/.Resources/RubberFS/$name/dev/StorageBlockDevice1"
    truncate -s 3T "/Wreathe/.Resources/RubberFS/$name/dev/StorageBlockDevice2"
    truncate -s 3T "/Wreathe/.Resources/RubberFS/$name/dev/StorageBlockDevice3"
    zpool create "$name" mirror "/Wreathe/.Resources/RubberFS/$name/dev/StorageBlockDevice1" "/Wreathe/.Resources/RubberFS/$name/dev/StorageBlockDevice2" "/Wreathe/.Resources/RubberFS/$name/dev/StorageBlockDevice3"
    zfs set compression=gzip-9 "$name"
    zfs set relatime=on "$name"
    (
        cd "/$name"
        touch README.md
    )
    chown "$(rubberfsUser):$(rubberfsUser)" "/$name"
    chown -R "$(rubberfsUser):$(rubberfsUser)" "/$name/.git"
    #sudo -u "$rubberfsUser" git init
    rubberfs snapshot "$name"
    rubberfs check "$name"
    rubberfs unmount "$name"
    echo "RubberFS named $name has been created. Run rubberfs mount $name to mount it."
    ;;
mount)
    #TODO: Also mount a FUSE filesystem that replaces .crystals with symlinks to a FUSE filesystem hooked up to IA's S3 API, somehow.
    zpool import -d "/Wreathe/.Resources/RubberFS/$name/dev/" "$name"
    zpool scrub "$name"
    ln -s -T -f "/$name" "/Wreathe/.Resources/RubberFS/$name/mount"
    #rubberfs cd "$name"
    echo "RubberFS named $name has been mounted."
    ;;
cd)
    echo "D'oh! Your bash_setup doesn't seem to have been run or worked."
    ;;
unmount)
    rubberfs save "$name"
    zpool export "$name"
    echo "RubberFS named $name has been unmounted."
    ;;
attach)
    username="$1"
    server="$2"
    prefix="$3"
    mountpoint="$4"
    sshfs -o allow_other,defer_permissions "$username"@"$server":"/Wreathe/.Resources/RubberFS/$prefix/mount/" "$mountpoint"
    ;;
check)
    zpool scrub "$name"
    echo "A check for RubberFS named $name has been begun; use rubberfs status $name to see its progress."
    ;;
save)
    cd "/$name"
    touch README.md
    #sudo -u "$rubberfsUser" git add -A .
    #set +e
    #sudo -u "$rubberfsUser" git commit -a -m "RubberFS: make snapshot"
    #sudo -u "$rubberfsUser" git pull
    #sudo -u "$rubberfsUser" git submodule update --remote
    #sudo -u "$rubberfsUser" git push -u origin master
    #set -e
    rubberfsSnapshot="rs$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
    zfs snapshot "$name@$rubberfsSnapshot"
    echo "A snapshot $rubberfsSnapshot in RubberFS named $name has been created."
    ;;
freeze)
    #TODO: make sure this works. What it should do: Back up the complete current filesystem to IA (as a .crystal but don't keep local copy), put the .crystal in the .rubberfs/history/ folder, and remove old snapshots.
    if mount | grep "/$name" > /dev/null; then
        umount "/$name"
    fi
    if mount | grep "/$name" > /dev/null; then
        echo "Unmounting failed!"
        exit 1
    fi
    freezeId="rs$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
    crystalWorkdir=$(crystallize-getconf 'WorkDirectory')
    freezeUuid="$(python -c 'import uuid; print str(uuid.uuid4())')"
    zfs snapshot -r "$name@$freezeId"
    zfs send -R "$name@$freezeId" > "$crystalWorkdir/$name@$freezeId.$freezeUuid.zfsrepl"
    smallify "$crystalWorkdir/$name@$freezeId.$freezeUuid.zfsrepl"
    rubberfs mount "$name"
    rsync -av --progress --checksum "$crystalWorkdir/$name@$freezeId.$freezeUuid.zfsrepl.crystal" "$crystalWorkdir/.$name@$freezeId.$freezeUuid.zfsrepl.crystal-data" "$name/.rubberfs/history/"
    freezeCrystal="$(cat "$crystalWorkdir/.$name@$freezeId.$freezeUuid.zfsrepl.crystal-data/identifier")"
    echo "$name@$freezeId" > "$name/.rubberfs/lastFullFreeze"
    echo "$freezeUuid" > "$name/.rubberfs/lastFullFreezeUuid"
    echo "$freezeCrystal" > "$name/.rubberfs/lastFullFreezeCrystal"
    rubberfs snapshot
    rubberfs unmount
    echo "A snapshot $freezeCrystal of RubberFS named $name has been created."
    ;;
freeze-delta)
    #TODO?: Convert old ZFS snapshots to single files that can be crystallized and then pulled back into the ZFS filesystem later. Is this possible?
    ;;
status)
    zpool list "$name"
    zpool status "$name"
    df -i /"$name"
    #zfs list -ro space -t snapshot
    zfs list -ro space "$name"
    ;;
list)
    zfs list -t snapshot
    rubberfs status "$name"
    ;;
stub)
    if [ ! -e /Ember\ Library ]; then
        mkdir -p /Ember\ Library/Futuramerlin\ Projects/Data/Crystal\ Index/
    else
        echo "There appears to already be an Ember Library instance available; no action taken."
        exit 1
    fi
    ;;
*)
    echo "Unknown action."
    exit 1
    ;;
esac
