#!/bin/bash

bin="$(dirname "$(readlink -f "$0")")"
prefix="$(dirname "$bin")"
prefix="$(dirname "$prefix")"
crystallizeDestdir=/crystallizeDestdir
crystallizePrefix=/crystallizePrefix
crystallizeCapPrefix=/crystallizeCapPrefix
crystallizeExecPrefix=/crystallizeExecPrefix
crystallizeBindir=/crystallizeBindir
crystallizeDatarootdir=/crystallizeDatarootdir
crystallizeDatadir=/crystallizeDatadir
crystallizeSysconfdir=/crystallizeSysconfdir
crystallizeSharedstatedir=/crystallizeSharedstatedir
case $1 in
    Bin)
        echo "$bin"
        ;;
    Sysconf)
        echo 
        ;;
    Sharedstate)
        echo 
        ;;
    *)
        exit 1
esac
