#!/bin/bash
# Crystallize

#Script must be run as root.

#Usage: crystallize-update

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

#Script should exit if any operation fails.
set -e

echo "Please wait until it says 'Done installing or updating crystallize'."

CrystalID=CrystallizeUpdate-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")-$(python -c 'import uuid; print str(uuid.uuid4())')
export CrystalID

mkdir -v ~/"$CrystalID".git-tmp
cd ~/"$CrystalID".git-tmp
git clone https://github.com/ethus3h/crystallize
git clone https://github.com/ethus3h/wreathe
git clone https://github.com/jjjake/internetarchive
cd internetarchive
find ../wreathe/etc/portage/patches/dev-python/internetarchive -name "*.patch" -exec patch -p1 -i {} \;
pip install --upgrade .

cp -v /usr/local/bin/crystallize-update "/usr/local/bin/crystallize-update.old.$CrystalID"
crystallize /usr/local/bin/crystallize /usr/local/bin/crystallize-logsession /usr/local/bin/crystallize-internal-xz /usr/local/bin/crystallize-internal-ia /usr/local/bin/crystallize-internal-xz-b /usr/local/bin/decrystallize /usr/local/bin/decrystallize-logsession /usr/local/bin/crystallize-rescue-tmp /usr/local/bin/crystallize-update-tmp "/usr/local/bin/crystallize-update.old.$CrystalID"
echo "Please wait; still updating..."

cd ../crystallize
make

exec /bin/bash -c 'sudo make install'
