#!/bin/bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
#set -x

xz -C sha256 -9 -e -v "${crystalWorkdir:?}/${CrystalID:?}".json
