#!/usr/bin/env bash

#set -x
set +o pipefail

configFileLocation="/usr/local/etc/crystallize.conf"

if [[ "$1" == "ConfigLocation" ]]; then
    echo "$configFileLocation"
    exit
fi

if [[ "$1" == "crystallizeVersion" ]]; then
    crystallizeVersionA="$(sed '6q;d' /usr/local/bin/crystallize)"
    crystallizeVersionB="${crystallizeVersionA%\'*}"
    echo "${crystallizeVersionB##*\'}"
    exit
fi

grep -n ^"$1", "$configFileLocation" | cut -f2 -d: | tail -1 | cut -f2 -d,
