#!/usr/bin/env bash
#set -x

defaultEditor="$(getDefaultEditorPath)"
configLocation="$(crystallize-getconf ConfigLocation)"
if [[ -w "$configLocation" ]]; then
    "$defaultEditor" -wLN "$configLocation"
else
    sudo -k "$defaultEditor" -wLN "$configLocation"
fi
