#!/bin/bash
set -e
set -x

echo "cd \"$(pwd)\""
echo "CrystalID=\"$CrystalID\""
echo "crystalWorkdir=\"$crystalWorkdir\""
echo "crystalTitle=\"$crystalTitle\""
echo "crystallizeVersion=\"$crystallizeVersion\""
echo "crystalCollection=\"$crystalCollection\""
tee /dev/null < "$crystalWorkdir/$CrystalID".coal5 | ia upload "$CrystalID" - --remote-name="$(basename "$crystalWorkdir/$CrystalID".coal5)" --verify --retries=100 --metadata="subject:Uploaded using Crystallize $crystallizeVersion" --metadata="subject:1EA21BD8-DB7E-11E5-9733-728C37852114" --metadata=subject:"$crystalTitle" --metadata=subject:"$CrystalID" --metadata="collection:$crystalCollection" 
echo "ECRh: $?"
