#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Will back up the Ember Library by default.
# Can optionally add additional things to back up: put a file for each other sreg repo (the .sreg folder, not the root) to back up in [ConfigDir]/.cbb.sreg/, a list of Crystal IDs to back up in [ConfigDir]/.cbb.crystals, a list of other IA identifiers to back up in [ConfigDir]/.cbb.idents, and a list of other git repositories to back up in [ConfigDir]/.cbb.repos.

backupLocation="crystallize-getconf BackupLocation"

mkdir -p "$backupLocation"

cd "$backupLocation"
touch ".cbb.isBackupDir"

cbbConfigDir="$(crystallize-getconf ConfigDir)"
mkdir -p "$cbbConfigDir"/.cbb.sreg
touch "$cbbConfigDir"/.cbb.sreg/.keep
touch "$cbbConfigDir"/.cbb.crystals
touch "$cbbConfigDir"/.cbb.idents
touch "$cbbConfigDir"/.cbb.repos

# Build backup indices (this won't finish building the sreg/crystal indices because they need the git repos cloned to make them)
mkdir -p ".cbb.idx/sreg-core"
rm -r ".cbb.idx/sreg-extra"
rsync -a --checksum "$cbbConfigDir"/.cbb.sreg ".cbb.idx/sreg-extra"
rsync -a --checksum "$cbbConfigDir"/.cbb.crystals ".cbb.idx/crystals"
rsync -a --checksum "$cbbConfigDir"/.cbb.idents ".cbb.idx/idents"
rsync -a --checksum "$cbbConfigDir"/.cbb.repos ".cbb.idx/repos"

echo "${EmberLibrary:?}/Futuramerlin Projects/Data/Stream Registry" >  ".cbb.idx/sreg-core/EmberLibrary"
echo "${EmberLibrary:?}/Ember satellite projects/ember-history/.sreg" >  ".cbb.idx/sreg-core/EmberHistory"
echo "${EmberLibrary:?}/Ember satellite projects/wreathe-packages/.sreg" >  ".cbb.idx/sreg-core/WreathePackages"

echo $'\n'"https://github.com/ethus3h/ember-meta.git" >>  ".cbb.idx/repos"

# Take care of git now
(
    mkdir git
    cd git
    cbbRepos="$(<.cbb.idx/repos)"
    while read -r repo; do
        git clone --recursive "$repo"
    done <<< "$cbbRepos"
) || die

for file in .cbb.idx/sreg-core/* .cbb.idx/sreg-extra/*; do
    bakDir="sregbak/${file:9}"
    mkdir -p "$bakDir"
    pathToSreg="$(<"$file")"
    mkdir -p "$pathToSreg/LocalStore"
    rsync -av --checksum "$pathToSreg/LocalStore" "$pathToSreg/passphrase" "$bakDir/"
    # Go through this sreg and add all the crystals it uses to the index
    for identFile in "$pathToSreg/Packs/"*.identifier; do
        # This gets the pack files
        echo "$(<"$identFile")" >> ".cbb.idx/crystals"
    done
    
done
