#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

check="true"
if [[ "$1" == "--no-check-existing" ]]; then
    check="false"
    shift
fi

backupLocation="$(crystallize-getconf BackupLocation)"

mkdir -p "$backupLocation"

echo 'Building backup indices'

cd "$backupLocation" || die "Could not cd to newly created directory! This should never happen."
touch ".cbb.isBackupDir"

[[ -e '.git' ]] || git init
print $'items\n' >> .gitignore
print $'items.failed-check\n' >> .gitignore
print $'repositories\n' >> .gitignore
print $'stream-registries\n' >> .gitignore
removeDuplicateLines '.gitignore' | sponge '.gitignore'

git add .gitignore
git commit -m "Update" > /dev/null || true
git add -A .
git commit -m "Update" > /dev/null || true

cbbConfigDir="$(crystallize-getconf ConfigDir)"
touch "$cbbConfigDir"/crystallize/cbb/items
touch "$cbbConfigDir"/crystallize/cbb/repositories
touch "$cbbConfigDir"/crystallize/cbb/stream-registries

mkdir -p 'crystal-backup-meta/cbb-index'
mkdir -p 'items'
mkdir -p 'repositories'
mkdir -p 'stream-registries'

# Build backup indices (this won't finish building the sreg/crystal indices because they need the git repos cloned to make them)
echo 'Syncing configuration...'

rsync -a --checksum "$(crystallize-getconf ConfigLocation)" "crystal-backup-meta/cbb-index/ember.conf" &> /dev/null
crystallize-getconf 'passphrase' > "crystal-backup-meta/cbb-index/passphrase.default"

# FIXME: Recursively cloning ember-meta doesn't seem to work, for some reason.
echo $'\n'"https://github.com/ethus3h/ember-meta.git" >>  "crystal-backup-meta/cbb-index/repositories"
echo $'\n'"https://github.com/ethus3h/ember-library-2.git" >>  "crystal-backup-meta/cbb-index/repositories"

echo $'\n'"ember-library-2/Futuramerlin Projects/Data/Stream Registry" >>  "crystal-backup-meta/cbb-index/stream-registries"
echo $'\n'"ember-history/.sreg" >>  "crystal-backup-meta/cbb-index/stream-registries"
echo $'\n'"wreathe-packages/.sreg" >>  "crystal-backup-meta/cbb-index/stream-registries"

print $'\n' >> "crystal-backup-meta/cbb-index/items"
cat "$cbbConfigDir"/crystallize/cbb/items >> "crystal-backup-meta/cbb-index/items"
removeDuplicateLines 'crystal-backup-meta/cbb-index/items' | sponge 'crystal-backup-meta/cbb-index/items'

print $'\n' >> "crystal-backup-meta/cbb-index/repositories"
cat "$cbbConfigDir"/crystallize/cbb/repositories >> "crystal-backup-meta/cbb-index/repositories"
removeDuplicateLines 'crystal-backup-meta/cbb-index/repositories' | sponge 'crystal-backup-meta/cbb-index/repositories'

print $'\n' >> "crystal-backup-meta/cbb-index/stream-registries"
cat "$cbbConfigDir"/crystallize/cbb/stream-registries >> "crystal-backup-meta/cbb-index/stream-registries"
removeDuplicateLines 'crystal-backup-meta/cbb-index/stream-registries' | sponge 'crystal-backup-meta/cbb-index/stream-registries'

# Clone git repositories
(
    mkdir -p repositories
    cbbRepos="$(<crystal-backup-meta/cbb-index/repositories)"
    cd repositories
    while read -r repo; do
        repoName="$(basename "$repo")"
        repoName="${repoName%.*}"
        if [[ -n "$repoName" ]]; then
            if [[ -e "$repoName" ]]; then
                (
                    cd "$repoName"
                    echo "Updating clone of the \"$repoName\" git repository..."
                    git pull || die
                    git submodule update --init --recursive || true
                    git submodule update --recursive
                )
            else
                git clone --recursive "$repo" || die
            fi
        fi
    done <<< "$cbbRepos"
) || die

shopt -s dotglob

cbbStreamRegistries="$(<crystal-backup-meta/cbb-index/stream-registries)"
while read -r streamRegistryPath; do
    if [[ -n "$streamRegistryPath" ]]; then
        ln -s "$streamRegistryPath" "stream-registries/$(basename "$streamRegistryPath")"
        # Go through this sreg and add all the crystals it uses to the index

        # Normal remote pack pointers
        for identFile in "$pathToSreg/Packs/"*.identifier; do
            #echo "$(<"$identFile")" >> "crystal-backup-meta/cbb-index/items"
            true # (Skipping ident file since this is disabled right now to make testing faster)
            # FIXME: won't work for packs that don't have a .identifier file (older ones just have a pointer file)
        done

        # TODO: Not implemented
        # Remote pack pointers, with pointer data in the pointer [209fcfdf-d1ad-4345-8ef7-1fdc2d583d49]
        # Like the normal remote pack pointers, we need to get the identifier out of the pointer as a tar file.

        # Standard remote pointers [a5e2f296-3085-49c0-8f48-24ea436b7a8b]
        # URL pointers [45baff46-8db7-46f6-aad9-de5f713b02fe]
        shopt -s globstar
        # for potentialPointer in "$pathToSreg"/**; do
        #     if [[ -f "$potentialPointer" ]]; then
        #         typeSignature="$(head -c 36 "$potentialPointer" | tr -d '\0')"
        #         if [[ "$typeSignature" == "a5e2f296-3085-49c0-8f48-24ea436b7a8b" ]]; then # Standard remote pointer
        #             true # TODO: Not implemented
        #         elif [[ "$typeSignature" == "45baff46-8db7-46f6-aad9-de5f713b02fe" ]]; then # URL pointer
        #             true # TODO: Not implemented
        #         fi
        #     fi
        # done
    fi
done <<< "$cbbStreamRegistries"

removeDuplicateLines 'crystal-backup-meta/cbb-index/items' | sponge 'crystal-backup-meta/cbb-index/items'

git add -A .
git commit -m "Update" > /dev/null || true

# Actually download and/or check the selected crystals now
mkdir -p "items"
cd items || die "Could not cd to newly created items directory"
cbbCrystals="$(<../crystal-backup-meta/cbb-index/items)"
while read -r crystal; do
    if [[ -n "$crystal" ]]; then
        if [[ -e "$crystal" ]]; then
            if [[ "$check" == "false" ]]; then
                continue
            fi
        fi
        crystallize-backup "$crystal"
    fi
done <<< "$cbbCrystals"

git add -A .
git commit -m "Update" > /dev/null || true
