#!/bin/bash
# Crystallise

#Script must be run as root.

#Usage: crystallise-update

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

#Script should exit if any operation fails.
set -e

CrystalID=CrystalliseUpdate-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")-$(python -c 'import uuid; print str(uuid.uuid4())')
export CrystalID

echo "Please wait until the script says \"Done updating!\"..."

pip install --upgrade git+https://github.com/ethus3h/internetarchive

ls -las /usr/local/bin
touch /usr/local/bin/crystallise-rescue-tmp
touch /usr/local/bin/crystallise-update-tmp

cp -v /usr/local/bin/crystallise-update /usr/local/bin/crystallise-update.old.$CrystalID
crystallise /usr/local/bin/crystallise /usr/local/bin/crystallise-logsession /usr/local/bin/crystallise-internal-xz /usr/local/bin/crystallise-internal-ia /usr/local/bin/crystallise-internal-xz-b /usr/local/bin/decrystallise /usr/local/bin/decrystallise-logsession /usr/local/bin/crystallise-rescue-tmp /usr/local/bin/crystallise-update-tmp /usr/local/bin/crystallise-update.old.$CrystalID
echo "Please wait; still updating..."
mkdir -v ~/$CrystalID.tmp
cd ~/$CrystalID.tmp
wget --no-cache https://raw.githubusercontent.com/ethus3h/crystallise/master/scripts/crystallise
wget --no-cache https://raw.githubusercontent.com/ethus3h/crystallise/master/scripts/crystallise-rescue
wget --no-cache https://raw.githubusercontent.com/ethus3h/crystallise/master/scripts/crystallise-logsession
wget --no-cache https://raw.githubusercontent.com/ethus3h/crystallise/master/scripts/crystallise-internal-xz
wget --no-cache https://raw.githubusercontent.com/ethus3h/crystallise/master/scripts/crystallise-internal-ia
wget --no-cache https://raw.githubusercontent.com/ethus3h/crystallise/master/scripts/crystallise-internal-xz-b
wget --no-cache https://raw.githubusercontent.com/ethus3h/crystallise/master/scripts/decrystallise
wget --no-cache https://raw.githubusercontent.com/ethus3h/crystallise/master/scripts/decrystallise-logsession
wget --no-cache https://raw.githubusercontent.com/ethus3h/crystallise/master/scripts/quickliquid
wget --no-cache https://raw.githubusercontent.com/ethus3h/crystallise/master/scripts/dequicklify
chmod +x ./*
cp -v ./* /usr/local/bin/
cd ~
crystallise ~/$CrystalID.tmp
echo "Please wait; still updating..."
mkdir -v ~/$CrystalID.tmp
cd ~/$CrystalID.tmp
wget --no-cache https://raw.githubusercontent.com/ethus3h/crystallise/master/scripts/crystallise-update
chmod +x ./*

# Spawn update script — based on http://dirty-motherfucker.org/blog/2012/02/26/self-updating-bash-script-revised/
cat > /usr/local/bin/crystallise-update-tmp.sh << EOF
#!/bin/bash
# Overwrite old file with new
if cp -v ./* /usr/local/bin/; then
    cd ~

    #Clear the screen
    printf "\033c"

    echo "Done updating!"
else
    echo "Failed! This should generally not happen; please report it as a bug."
fi
EOF

chmod +x /usr/local/bin/crystallise-update-tmp.sh

echo -n "Inserting update process..."
exec /bin/bash /usr/local/bin/crystallise-update-tmp.sh
