#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

pattern="$1"

cd "${EmberLibrary:?}"/Futuramerlin\ Projects/Data/Crystal\ Index/
for file in ./*.deep.idx; do
    if grep -q "$pattern" "$file"; then
        echo "Found $(grep -v '^#' "$file" | grep "$pattern" | cut -d ',' -f 5- -) in crystal:"
        fileName="${file/\.\/}"
        echo "${fileName%\.deep\.idx}"
    fi
done
