#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# TODO: Detect if output is not to a terminal and cat instead of less

pathPrefix="${EmberLibrary:?}"/Futuramerlin\ Projects/Data/Crystal\ Index/"$1"
if ! [[ -e "$pathPrefix".csum ]]; then
    fcache_request "$crystalWorkdir/.CrystalCache/" "https://archive.org/download/$CrystalID/$CrystalID.csum" > "$pathPrefix".csum
    if [[ "$?" != "0" ]]; then
        emdate > "$pathPrefix".csum-not-found
    fi
fi

if [[ -e "$pathPrefix".csum-not-found ]]; then
    less "$pathPrefix".csum
else
    less "$pathPrefix".deep.idx
fi
