#!/usr/bin/env bash
#set -x

nanoLocation="$(which "nano")"
nanoFileToEdit="$(crystallize-getconf ConfigLocation)"
if [[ -w "$nanoFileToEdit" ]]; then
    "$nanoLocation" -wLN "$nanoFileToEdit"
else
    sudo -k "$nanoLocation" -wLN "$nanoFileToEdit"
fi
