#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

ia upload "${CrystalID:?}" --verify --retries=100 --metadata="title:Crystal Document Package: ${CrystalID:?}" --metadata="description:This is a structured package containing documents and metadata about them and their provenance. To learn more about Crystal packages and working with them, see the description on the collection page." --metadata="subject:Uploaded using Crystallize ${crystallizeVersion:?}" --metadata="subject:Crystallize using ember-shared version ${emberSharedVersion:?}" --metadata="subject:1EA21BD8-DB7E-11E5-9733-728C37852114" --metadata=subject:"${crystalTitle:?}" --metadata=subject:"${CrystalID:?}" --metadata="collection:${crystalCollection:?}" "${CrystalTmpUploadFile:?}"
