#!/bin/bash
set -e
echo
echo
#get available memory
memlimit=-1
if hash free 2>/dev/null; then
    if free | grep -q buff/cache; then
        #free has one column for buffers and cache
        memlimit="$(free | grep Mem: | awk 'FNR == 1 {print ($4+$6)}')"
    else
        #free has separate columns for buffers and cache
        memlimit="$(free | grep Mem: | awk 'FNR == 1 {print ($4+$6+$7)}')"
    fi
    #Output is in kilobytes
    memlimit="$(($memlimit * 1000))"
elif hash vm_stat 2>/dev/null; then
    #The system doesn't have the free command; try vm_stat
    #use sum of free+inactive from vm_stat
    freel="$(vm_stat | grep "Pages free:" | awk 'FNR == 1 {print ($3)}')"
    free="${freel::${#freel}-2}"
    inactivel="$(vm_stat | grep "Pages inactive:" | awk 'FNR == 1 {print ($3)}')"
    inactive="${inactivel::${#inactivel}-2}"
    memlimit="$(($free + $inactive))"
    #Output is in 4096-byte pages
    memlimit="$(($memlimit * 256))"
else
    echo "Warning: Could not determine how much memory is available."
    sleep 3
fi
memlimit="$(($memlimit - 1073741824))"
#xz -9 requires 13MB minimum
if [ $memlimit -lt 13631488 ]; then

    echo "### WARNING! ### WARNING! ### WARNING! ### WARNING! ### WARNING! ###"
    echo "There may not be enough free memory; compression may fail!"
    echo "Continuing in 10 seconds; press Ctrl+C to cancel."
    echo "### WARNING! ^^^ WARNING! ### WARNING! ### WARNING! ^^^ WARNING! ###"
    sleep 10

    xz -k -C sha256 -T 0 --lzma2=preset=9 -v "$crystalWorkdir/$CrystalID".pax
else
    xz -k -C sha256 -T 0 --lzma2=preset=9 --memlimit-compress="$memlimit" -v "$crystalWorkdir/$CrystalID".pax
fi
