#!/usr/bin/env bash
#set -x

export emberCrystallizeVersion='3.1.2.5.14.360'

# The update script shown here requires there to be only one ebuild of crystallize in the wreathe-overlay overlay.
# ( sudo true; newVersion="3.1.2.5.14.360"; cd "/Ember/crystallize"; echo "$newVersion" > version; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember/wreathe-overlay"; eogup-single; mv app-misc/crystallize/crystallize-*.ebuild "app-misc/crystallize/crystallize-$newVersion.ebuild"; repoman manifest; egup-single; sudo emerge --sync wreathe-overlay; sudo emerge crystallize; sudo dispatch-conf; cd "$emberPath/ember-shared"; generateGuixPackaging crystallize; eogup-single; git push; )

# Note: To debug crystal retrieval when srpulling etc, change is needed to the following line in sreg_read_stream: decrystallize-pointer --passphrase "$(sregi_get_passphrase "$sregDir")" "$lockOverride" ./*.crystal --here &> /dev/null
# and in localstorecache_request: decrystallize --passphrase "$(sregi_get_passphrase "$sregDir")" "$crystalIdentifier" --here # &> /dev/null
# and in decrystallize: {
    #     fcache_request "$crystalWorkdir/.CrystalCache/" "https://archive.org/download/$CrystalID/$CrystalID.coal5-csum" | pv -tparbIfei 0.1 | gpg --yes --batch --passphrase-file "$tempId.tmp" - | unxz --stdout - > "$tempId.csum"
    #    exitStatus="$?"
    # } 2>/dev/null


rubberfs() {
    if [[ "$1" == "cd" ]]; then
        name="$2"
        if [[ -z "$name" ]]; then
            name="library"
        fi
        cd "/Wreathe/.Resources/RubberFS/$name/mount" || exit 1
    else
        "$(which rubberfs)" "$@"
    fi
}

git-absolute-path() {
    fullpath="$(readlink -f "$1")"
    gitroot="$(git rev-parse --show-toplevel)" || return 1
    [[ $fullpath == *$(printf %q "$gitroot")* ]] && echo "${fullpath/$gitroot\//}"
}

git-escape-path() {
    # (doesn't handle the case of the bash variable containing exactly one newline and that newline not being at the end)
    if [[ "$(wc -l <<< "$1")" == "1" ]] || [[ "$(wc -l <<< "$1")" == "0" ]]; then
        sed 's/./&\\/g' <<< "$1" | awk '{print "\\"$1}' | sed 's/.$//'
    else
        exit 1
    fi
}

iu() {
    quickliquid "$@"
}

crystallize_quick_unpack() {
    local fileToUnpack
    local destDir=""
    local unpackDate
    unpackDate="$(emdate)"
    if [[ "$1" == "--to" ]]; then
        shift
        destDir="$1/$unpackDate.unpack"
        shift
    fi
    fileToUnpack="$1"
    if [[ "$2" == "--to" ]]; then
        destDir="$3/$unpackDate.unpack"
        [[ -n "$4" ]] && { error-notify "Sorry, only one file can be unpacked at a time by crystallize_quick_unpack."; return 1; }
    else
        [[ -n "$2" ]] && { error-notify "Sorry, only one file can be unpacked at a time by crystallize_quick_unpack."; return 1; }
    fi
    [[ -n "$fileToUnpack" ]] && mkdir -p "$destDir/$(dirname "$fileToUnpack")"
    local crystallizePassphrase
    crystallizePassphrase="$(crystallize-getconf Passphrase)"
    local passphraseTempfile
    passphraseTempfile="$(tempFile)"
    printf "%s" "$crystallizePassphrase" > "$passphraseTempfile"
    gpg --yes --batch --passphrase-file "$passphraseTempfile" - < "$fileToUnpack" > "$destDir/$fileToUnpack.unpacked-$unpackDate.unpacked" || { printf "%s" "example-crystal-passphrase" > "$passphraseTempfile"; gpg --yes --batch --passphrase-file "$passphraseTempfile" - < "$fileToUnpack" > "$destDir/$fileToUnpack.unpacked-$unpackDate.unpacked"; }
    unxz --stdout - < "$destDir/$fileToUnpack.unpacked-$unpackDate.unpacked" > "$destDir/$fileToUnpack.unpacked-$unpackDate.unpacked.unxz" || { echo "(Unxz failed; either the file wasn't compressed or is broken.)"; rm "$destDir/$fileToUnpack.unpacked-$unpackDate.unpacked.unxz"; }
    [[ -e "$destDir/$fileToUnpack.unpacked-$unpackDate.unpacked.unxz" ]] && mv "$destDir/$fileToUnpack.unpacked-$unpackDate.unpacked.unxz" "$destDir/$fileToUnpack.unpacked-$unpackDate.unpacked"
    echo "Done quick unpacking; result is at $destDir/$fileToUnpack.unpacked-$unpackDate.unpacked."
}

#Function is defined with parentheses to make it run in a subshell to prevent the "die" affecting the calling script (the calling script should be responsible for trapping/handling nonzero exit codes itself)
sregi_available_by_hash() (
    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

    local sregDir=""
    if [[ "$1" == "--sreg-dir" ]]; then
        shift
        sregDir="$1"
        shift
    fi
    sregDir="$(sregi_find_dir --sreg-dir "$sregDir")"

    local knownChecksum="$1"
    local hashA="${knownChecksum:0:1}"
    local hashB="${knownChecksum:1:1}"
    local hashC="${knownChecksum:2:1}"
    if [[ -n "$2" ]]; then
        local availByHashPointerFile="$2"
    else
        local availByHashPointerFile="$sregDir/$hashA/$hashB/$hashC/$knownChecksum"
    fi
    if ! [[ -e "$availByHashPointerFile" ]]; then
        die "Item does not have the corresponding stream registry entry $availByHashPointerFile!"
    fi
    local innerPointerTypeSignature
    innerPointerTypeSignature="$(head -c 36 "$availByHashPointerFile")"
    if [[ "$innerPointerTypeSignature" == "c39f8657-384b-438b-a5a2-eece17147589" ]]; then
        if ! [[ -f "$sregDir/LocalStore/$hashA/$hashB/$hashC/$knownChecksum" ]]; then
            die "Item does not have the corresponding LocalStore entry $sregDir/LocalStore/$hashA/$hashB/$hashC/$knownChecksum!"
        fi
    fi
)

# Function is defined with parentheses to avoid dumping the enclosed function definition into the calling script
sregi_hash_from_file() (
    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

    file="$1"
    sregi_hash_from_file_pipecheck() {
        (
            pipeCheckTemp=("${PIPESTATUS[@]}")
            if [[ "${pipeCheckTemp[0]}" != "141" ]] && [[ "${pipeCheckTemp[0]}" != "0" ]]; then
                # Ignore status 141, which just means the input stream was terminated by head before all the data were consumed
                die "Failed reading temporary stream file"
            fi
            if [[ "${pipeCheckTemp[1]}" != "0" ]]; then
                die "Failed executing head on temporary stream file"
            fi
        )
    }
    local pointerTypeSignature
    pointerTypeSignature="$(head -c 36 "$file" | tr -d '\0')"
    if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]] || # Hash pointer
        [[ "$pointerTypeSignature" == "a5e2f296-3085-49c0-8f48-24ea436b7a8b" ]] || # Standard remote pointer
        [[ "$pointerTypeSignature" == "c39f8657-384b-438b-a5a2-eece17147589" ]] || # LocalStore pointer
        [[ "$pointerTypeSignature" == "2fae2004-94bb-4aa8-a01a-fc44298efc2c" ]] || # Remote pack pointer
        [[ "$pointerTypeSignature" == "209fcfdf-d1ad-4345-8ef7-1fdc2d583d49" ]] || # Remote pack pointer, with pointer data in the pointer
        [[ "$pointerTypeSignature" == "45baff46-8db7-46f6-aad9-de5f713b02fe" ]] # URL pointer
    then
        set +o pipefail
        tail -c +38 "$file" | head -c 129
        sregi_hash_from_file_pipecheck
        set -o pipefail
    else
        # It's a regular file, not a pointer, so just get its sha512sum.
        # FIXME: Should this have pipefail? Should the general pipecheck be used for it? What about other pipes in crystallize, and in bash scripts in general?
        set +o pipefail
        sha512sum < "$file" | awk '{print $1;}'
        set -o pipefail
    fi
)

EmberLibrary="$(crystallize-getconf EmberLibrary)"
