#!/bin/bash

configFileLocation="/usr/local/etc/crystallize.conf"

if [[ "$1" == "ConfigLocation" ]]; then
    echo "$configFileLocation"
fi

grep -n ^"$1", "$configFileLocation" | cut -f2 -d: | tail -1 | cut -f2 -d,
