#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# TODO: Detect if output is not to a terminal and cat instead of less
# TODO: Add support for fetching index files for crystals that aren't available in the index

pathPrefix="${EmberLibrary:?}"/Futuramerlin\ Projects/Data/Crystal\ Index/"$1"
if [[ -e "$pathPrefix".csum ]]; then
    less "$pathPrefix".deep.idx 2>/dev/null || less "$pathPrefix".csum
else
    fcache_request "$crystalWorkdir/.CrystalCache/" "https://archive.org/download/$CrystalID/$CrystalID.csum" > 
