#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

# Usage: crystallize-backup <crystal-address>

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

shopt -s extglob

#Remove URL
CrystalAddress="${1#https://archive.org/@(details|download)/}"
#Remove trailing path(s) from identifier
CrystalAddress="${CrystalAddress%%/*}"
CrystalAddress="${CrystalAddress%\.coal5*}"

if [[ "$CrystalAddress" == "" ]]; then
    echo "Please specify a crystal address to back up."
    exit 1
fi

CrystalID="$CrystalAddress"

echo "Crystal address: $CrystalID"

if [[ -e "$CrystalID" ]]; then
    exit 1
fi
mkdir "$CrystalID"
(
    cd "$CrystalID" || die "Could not cd to newly created folder! This should never happen."
    crystallize-getconf Passphrase > "$CrystalID.passphrase"
    wget "https://archive.org/download/$CrystalID/$CrystalID.coal5"
    wget "https://archive.org/download/$CrystalID/$CrystalID.coal5-cmd"
    wget "https://archive.org/download/$CrystalID/$CrystalID.coal5-cwd"
    wget "https://archive.org/download/$CrystalID/$CrystalID.coal5-idx-d"
    wget "https://archive.org/download/$CrystalID/$CrystalID.coal5-idx-l"
    wget "https://archive.org/download/$CrystalID/$CrystalID.coal5-log"
    wget "https://archive.org/download/$CrystalID/$CrystalID.coal5-timestamp"
    wget "https://archive.org/download/$CrystalID/$CrystalID"_files.xml
    wget "https://archive.org/download/$CrystalID/$CrystalID"_meta.sqlite
    wget "https://archive.org/download/$CrystalID/$CrystalID"_meta.xml
)
echo "Done! The crystal has been backed up to $CrystalID."
