#!/usr/bin/env emberPlatformResolver bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
streamId="703b3f58-57de-4b8d-b0a9-b5931b37458a"
finish() {
    if [[ -e "/tmp/${streamId:?}" ]]; then
        rm "/tmp/${streamId:?}"
    fi
}
trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; finish; exit 1' ERR
trap finish EXIT

action="$1"

if [[ -z "$action" ]]; then
    action="save"
fi

case $action in
save)
    setVariableToCommandOutput currentworkingdir pwd -P
    currentworkingdir="${currentworkingdir:?}"
    currentworkingdir="${currentworkingdir//$'\n'/'\n'}"
    if [[ -z "$2" ]]; then
        printf "%s\n" "${currentworkingdir//$'\r'/'\r'}"
        hashdeep -c md5,sha1,sha256,tiger,whirlpool -j0 -e -o fbsd -r -l .
    else
        printf "%s\n" "${currentworkingdir//$'\r'/'\r'}" > "$2"
        hashdeep -c md5,sha1,sha256,tiger,whirlpool -j0 -e -o fbsd -r -l . >> "$2"
    fi
    ;;
check)
    streamId="csum-$(date-uuid)"
    if [[ -z "$2" ]]; then
        sponge "/tmp/$streamId"
    else
        tail -n +2 "$2" > "/tmp/$streamId"
    fi
    hashdeep -k "/tmp/$streamId" -e -o fbsd -r -l -a -v -v .
    finish
    ;;
*)
    echo "Unknown action."
    exit 1
    ;;
esac
