#!/bin/bash
# decrystallize-pipe

# See crystallize for requirements.

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

#Script should exit if any operation fails.
set -e

shopt -s extglob

crystalWorkdir=$(crystallize-getconf 'WorkDirectory')

CrystalAddress="$(cat $1)"

CrystalLogID=$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")-$(python -c 'import uuid; print str(uuid.uuid4())')

crystallizePassphrase=$(crystallize-getconf 'Passphrase')
printf "%s" "$crystallizePassphrase" > "$crystalWorkdir/$CrystalLogID.tmp"

mkfifo "$crystalWorkdir/$CrystalLogID.tar"
mkdir -p "$crystalWorkdir/$CrystalLogID.avfs"
avfsd "$crystalWorkdir/$CrystalLogID.avfs"
cp "$(which decrystallize-unpipe)" "$1-unmount"

wget -O - -o /dev/null "https://archive.org/download/$CrystalID/$CrystalID.coal5" | gpg --yes --batch --passphrase-file "$crystalWorkdir/$CrystalLogID.tmp" - | unxz > "$crystalWorkdir/$CrystalLogID.tar"
