#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

useCustomPassphrase="false"
customPassphrase=""
if [[ "$1" == "--passphrase" ]]; then
    useCustomPassphrase="true"
    shift
    customPassphrase="$1"
    shift
fi

lockOverride="--no-lock-override"
if [[ "$1" == "--no-lock-override" ]]; then
    shift
elif [[ "$1" == "--lock-override" ]]; then
    lockOverride="--lock-override"
    shift
fi

decrystallizeHere=""
if [[ "$2" == "--here" ]]; then
    decrystallizeHere="--here"
fi

identifier="$(crystallize-get-identifier-from-pointer "$1")"

if [[ "$useCustomPassphrase" != "true" ]]; then
    decrystallize "$lockOverride" "$identifier" "$decrystallizeHere"
else
    decrystallize --passphrase "$customPassphrase" "$lockOverride" "$identifier" "$decrystallizeHere"
fi
