#!/bin/bash
# Decrystallizes a .crystal pointer directory. (Does not handle single-file pointers; use scache_read_stream instead.)
set -e
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

decrystallize "$(cat "$(dirname "$1")"/."$(basename "$1")"-data/identifier)"
