#!/bin/bash
# decrystallize-pointer

# See crystallize for requirements.

#Usage: decrystallize-pointer <crystal-directory> [--here]

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

#Script should exit if any operation fails.
set -e

shopt -s extglob

if [ "$2" == "--here" ]; then
    decrystallize "$(cat "$1"/identifier)" --easy-use --here
else
    decrystallize "$(cat "$1"/identifier)" --easy-use
fi
