#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

#Need to do egup-single for futuramerlin-web-toolkit before build to ensure updates to futuramerlin-web-toolkit are committed before running it
(
    EmberLibrary="$(crystallize-getconf EmberLibrary)"
    cd "$EmberLibrary"/Ember\ satellite\ projects/futuramerlin-web-toolkit || exit 1
    egup-single .
    cd "$EmberLibrary"/Ember/ember-web-site || exit 1
    eogup-single .
    futuramerlin-web-toolkit-build
    egup-single .
)
