#!/bin/bash

# More verbose debugging
PS4='+($?) $BASH_SOURCE:$FUNCNAME:$LINENO:'
export PS4

# shellcheck disable=SC1091
source crystallize-bash_setup

# These may not be available on non-Wreathe systems
source wreathe_bash_setup &> /dev/null
source bash_math_functions &> /dev/null
source futuramerlin-web-toolkit-s &> /dev/null
source egup-env &> /dev/null
