#!/bin/bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

# Create a cache directory. This is a naive caching layer for non-changing URLs.
# Usage: fcache_init <directory-name> <cache size limit in bytes>
# If the cache directory already exists, the current size limit will override the one provided as an argument.

((EUID)) && exec sudo -- "$0" "$@"
trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR

if [ -e "$1"/.fcache.limit ]; then
    exit 0
elif [ -d "$1" ]; then
    error-notify "Directory already exists and is not a cache directory."
    exit 1
fi
mkdir -p "$1"
echo "$2" > "$1"/.fcache.limit
echo "Done creating cache directory."
