#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

if [[ -e "$1"/.fcache.limit ]]; then
    exit 0
elif [[ -d "$1" ]]; then
    if ! isSubdirOf "$(crystallize-getconf WorkDirectory)" "$1"; then
        error-notify "Directory already exists and is not a cache directory."
        exit 1
    fi
fi

cacheLimit=""
if [[ "$2" == +([0-9]) ]]; then
    # The 2nd argument is a positive integer
    cacheLimit="$2"
else
    case $2 in
    s)
        cacheLimit=""
        ;;
    f)
        cacheLimit="5000000000"
        ;;
    localstore)
        cacheLimit=""
        ;;
    *
        die "The 2nd argument must be either a positive integer or a cache type (s, f, or localstore)."
        ;;
    ;;
    esac
fi

mkdir -p "$1/ByCount"

echo "$2" > "$1"/.fcache.limit
echo "Done creating cache directory."
