#!/bin/bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

# Get an item through the cache
# Usage: localstorecache_request <cache directory> <crystal identifier>

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
#set -x

crystalWorkdir="$(crystallize-getconf 'WorkDirectory')"
dbDir="$1"
crystalIdentifier="$2"
if [[ -z "$crystalIdentifier" ]]; then
    echo "Please specify a directory and a crystal identifier."
    exit 1
fi
hashFull="$(sha512sum <<< "$crystalIdentifier" | awk '{print $1;}')"
hashA="${hashFull:0:1}"
hashB="${hashFull:1:1}"
hashC="${hashFull:2:1}"
hashSubdir="$hashA/$hashB/$hashC"
hashDir="$dbDir/$hashSubdir"
mkdir -p "$hashDir"
dbLinkPath="$hashDir/$hashFull"

# Clean up if there's an error to avoid leaving a broken cache entry
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; rm -rf "$dbLinkPath" "$(readlink -e "$dbLinkPath")"' ERR

# Remove the least-used items from the cache until it fits within the alloted disk space
diskUsageLimit="$(<"$dbDir"/.localstorecache.limit)"
diskUsageLimitSub=$(( diskUsageLimit - 1000000000 ))
if [[ "$(du -sb "$dbDir" | awk '{print $1;}')" -gt "$diskUsageLimit" ]]; then
    while [[ "$(du -sb "$dbDir" | awk '{print $1;}')" -gt "$diskUsageLimitSub" ]]; do
        rm "$dbDir"/Failed\ Checksum/*
        # Remove the least-used item from the cache
        leastUsedItemDirectory="$(find "$dbDir/ByCount" -maxdepth 1 -type d | sort -n | head -n 2 | tail -n 1)"
        #FIXME: This won't accurately sort by size.
        largestLeastUsedItem="$(find "$leastUsedItemDirectory" -maxdepth 4 -type d -printf "%s\t%p\n" | sort -n | tail -1 | awk '{print $2;}')"
        leastUsedItemCount="$(basename "$leastUsedItemDirectory")"
        hashFull="$(basename "$largestLeastUsedItem")"
        rm -rf "$largestLeastUsedItem"
        hashA="${hashFull:0:1}"
        hashB="${hashFull:1:1}"
        hashC="${hashFull:2:1}"
        hashSubdir="$hashA/$hashB/$hashC"
        hashDir="$dbDir/$hashSubdir"
        dbLinkPath="$hashDir/$hashFull"
        rm -f "$dbLinkPath"
        echo "$leastUsedItemCount" > "$dbLinkPath"
    done
fi
trap - ERR
oldFilePath="$(readlink "$dbLinkPath")"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; rm -rf "$dbLinkPath" "$(readlink -e "$dbLinkPath")"' ERR
cacheEntryFileList=("$oldFilePath"/scache-*.LocalStore)
if [[ ! -h "$dbLinkPath" ]] || [[ ! -f "$oldFilePath" ]] || [[ ! -d "${cacheEntryFileList[0]}" ]]; then
    # Item is not in the cache, so add it

    # Make sure there isn't a dangling LocalStore content folder with no associated link
    find "$dbDir/ByCount" -maxdepth 2 -type d -name "$hashFull" -exec rm -rf {} \;
    if ! [[ -f "$dbLinkPath" ]]; then
        # Never seen this item before, so set the requestCount
        requestCount=1
    else
        requestCount="$(<"$dbLinkPath")"
        rm "$dbLinkPath"
    fi
    dbFileDir="$dbDir/ByCount/$requestCount/$hashSubdir"
    dbFilePath="$dbFileDir/$hashFull"
    rm -rf "$dbFilePath"
    mkdir -p "$dbFilePath"
    tempDirectoryName="$crystalWorkdir/localstorecache-request-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
    mkdir -p "$tempDirectoryName"
    (
        cd "$tempDirectoryName" || exit 1
        decrystallize "$crystalIdentifier" &> /dev/null
        mv ./* "$dbFilePath"
    )
    if [[ -h "$dbLinkPath" ]]; then
        rm "$dbLinkPath"
    fi
    ln -s "$dbFilePath" "$dbLinkPath"
fi
dbFilePath="$(readlink -e "$dbLinkPath")"
# First, make sure the link is good and fix it up if it's not.
if ! [[ -e "$dbFilePath" ]]; then
    rm "$dbLinkPath"
    find "$dbDir/ByCount" -maxdepth 2 -type d -name "$hashFull" -exec ln -s {} "$dbLinkPath" \;
    dbFilePath="$(readlink -e "$dbLinkPath")"
fi
dbFileOldPath="$dbFilePath"
dbFileDir="$(dirname "$dbFilePath")"
# Get the requestCount. There are three path components after it. I suspect there's a better way to do this.
oldCount="$(basename "$(dirname "$(dirname "$(dirname "$dbFileDir")")")")"
# Increment the item's requestCount.
requestCount=$(( oldCount + 1 ))
# First, get the names of where the file should go.
dbFileDir="$dbDir/ByCount/$requestCount/$hashSubdir"
dbFilePath="$dbFileDir/$hashFull"
mkdir -p "$dbFileDir"
mv "$dbFileOldPath" "$dbFilePath"
rm "$dbLinkPath"
ln -s "$dbFilePath" "$dbLinkPath"
# Return the data to the caller
echo "$dbLinkPath"
# Clean up empty directories
find "$dbDir" -type d -empty -delete
if [[ -d "$tempDirectoryName" ]]; then
    rm -r "$tempDirectoryName"
fi
