#!/bin/bash
source ember_bash_setup &> /dev/null

# Create a cache directory. This is a naive caching layer for LocalStore crystals.
# Usage: localstorecache_init <directory-name> <cache size limit in bytes>
# If the cache directory already exists, the current size limit will override the one provided as an argument.

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR

if [ -e "$1"/.localstorecache.limit ]; then
    exit 0
elif [ -d "$1" ]; then
    error-notify "Directory already exists and is not a cache directory."
    exit 1
fi
mkdir -p "$1"
echo "$2" > "$1"/.localstorecache.limit
echo "Done creating cache directory."
