#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

crystallizeVersion="$(crystallize-getconf crystallizeVersion)"

iuIdentifier="Liquid-$(date-uuid)"

crystalTitle="$(crystallize-getconf InstallationIdentifier)"

ia upload "$iuIdentifier" --verify --metadata="subject:Uploaded using quickliquid for Crystallize $crystallizeVersion" --metadata="subject:9F227910-A541-11E5-8BD3-7B584224FF49" --metadata="subject:$crystalTitle" "$@"

tail=""
if [[ -z "$2" ]]; then
    tail="$(urlencode "$(basename "$1")")"
fi
echo "https://archive.org/download/$iuIdentifier/$tail"
