#!/usr/bin/env emberPlatformResolver bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

crystallizeVersion="$(crystallize-getconf crystallizeVersion)"

iuIdentifier="Liquid-$(date-uuid)"

crystalTitle="$(crystallize-getconf InstallationIdentifier)"

ia upload "$iuIdentifier" --verify --metadata="subject:Uploaded using quickliquid for Crystallize $crystallizeVersion" --metadata="subject:9F227910-A541-11E5-8BD3-7B584224FF49" --metadata="subject:$crystalTitle" "$@"

tail=""
if [[ -z "$2" ]]; then
    tail="$(urlencode "$(basename "$1")")"
fi
echo "https://archive.org/download/$iuIdentifier/$tail"
