#!/bin/bash
rubberfs() {
    if [[ "$1" == "cd" ]]; then
        name="$2"
        if [ ! -n "$name" ]; then
            name="library"
        fi
        cd "/Wreathe/.Resources/RubberFS/$name/mount"
    else
        rubberfs "$@"
    fi
}
export -f rubberfs
