#!/bin/bash
rubberfs() {
    if [[ "$1" == "cd" ]]; then
        name="$2"
        if [ ! -n "$name" ]; then
            name="library"
        fi
        cd "/Wreathe/.Resources/RubberFS/$name/mount"
    else
        "$(which rubberfs)" "$@"
    fi
}
export -f rubberfs

git-absolute-path () {
    fullpath="$(readlink -f "$1")"
    gitroot="$(git rev-parse --show-toplevel)" || return 1
    [[ "$fullpath" =~ "$gitroot" ]] && echo "${fullpath/$gitroot\//}"
}
export -f git-absolute-path
