#!/bin/bash
rubberfs() {
    if [[ "$1" == "cd" ]]; then
        name="$2"
        if [ ! -n "$name" ]; then
            name="library"
        fi
        cd "/Wreathe/.Resources/RubberFS/$name/mount" || exit 1
    else
        "$(which rubberfs)" "$@"
    fi
}
export -f rubberfs

git-absolute-path () {
    fullpath="$(readlink -f "$1")"
    gitroot="$(git rev-parse --show-toplevel)" || return 1
    [[ $fullpath == *$(printf %q "$gitroot")* ]] && echo "${fullpath/$gitroot\//}"
}
export -f git-absolute-path

git-escape-path () {
    # (doesn't handle the case of the bash variable containing exactly one newline and that newline not being at the end)
    if [[ "$(wc -l <<< "$1")" == "1" ]] || [[ "$(wc -l <<< "$1")" == "0" ]]; then
        sed 's/./&\\/g' <<< "$1" | sed 's/.$//'
    else
        exit 1
    fi
}
export -f git-escape-path

qlstash () {
    (
        elenv
        cd "$(dirname $(readlink -f "$1"))"
        rubberfs stash "$1"
        egup-exit
    )
}
export -f qlstash
