#!/bin/bash

crystallizeAccessKey="$(grep access ~/.config/ia.ini | head -n 1 | awk '{ print $3 }')"
crystallizeSecretKey="$(grep secret ~/.config/ia.ini | head -n 1 | awk '{ print $3 }')"

hostName="$1"
shift
collection="$1"
shift
identifier="$1"
shift
remoteFileName="$1"
shift
fileSizeEstimate="$1"
shift
title="$1"
shift
description="$1"
shift
keywords="$1"

#Cannot have more than 10,000 chunks.
chunkSize=$((fileSizeEstimate / 10000))
#Cannot have chunk size less than 5MB.
if [ $chunkSize -lt 5242880 ]; then
    chunkSize=5242880
fi

#Make bucket
echo -n "a" | curl --location --raw -X PUT --data-binary @- --header "x-amz-auto-make-bucket:1" --header "x-archive-queue-derive:0" --header "x-archive-size-hint:$fileSizeEstimate" --header "authorization: LOW $crystallizeAccessKey:$crystallizeSecretKey" --header "x-archive-meta-collection:$collection" --header "x-archive-meta-title:$identifier" --header "x-archive-meta-description:$description" --header "x-archive-meta-subject:$keywords" "http://$hostName/$identifier/.s3-streaming-upload.placeholder"

#Initialize streaming upload
aws --endpoint-url="$hostName" s3api create-multipart-upload --bucket="$identifier" --key="$remoteFileName"



complete-multipart-upload
