#!/bin/bash
source "$(which ember_bash_setup)" &> /dev/null

# Accepts a pointer as an argument, and crystallizes the file if it does not match its hash.
# Internal use only.

trap 'error-die "${BASH_SOURCE}" "${LINENO}"' ERR

knownHash="$(basename "$1")"
recoveredHash="$(sha512sum < "$1" | awk '{print $1;}')"
if [[ "$knownHash" != "$recoveredHash" ]]; then
    pointerTypeSignature="$(head -c 36 "$1")"
    if [[ "$pointerTypeSignature" != "a5e2f296-3085-49c0-8f48-24ea436b7a8b" ]] || [[ "$pointerTypeSignature" != "c39f8657-384b-438b-a5a2-eece17147589" ]] || [[ "$pointerTypeSignature" != "209fcfdf-d1ad-4345-8ef7-1fdc2d583d49" ]]; then
        warn "File failed backup verification!: $1"
        crystallize "$1"
    fi
fi
