#!/bin/bash
# Accepts a pointer as an argument, and crystallizes the file if it does not match its hash.
# Internal use only.
set -e
knownHash="$(basename "$1")"
recoveredHash="sha512sum "$1" | awk '{print $1;}'"
if [[ "$knownHash" != "$recoveredHash" ]]; then
    if [[ "$(head -c 36 "$1")" != "a5e2f296-3085-49c0-8f48-24ea436b7a8b" ]]; then
        warn "File failed backup verification!: $1"
        crystallize "$1"
    fi
fi
