#!/bin/bash
# Accepts a pointer as an argument, and replaces the file with the pointer's contents if it does not match its hash.
# Internal use only.
set -e
knownHash="$(basename "$1")"
recoveredHash="sha512sum "$1" | awk '{print $1;}'"
if [[ "$knownHash" != "$recoveredHash" ]]; then
    scache_read_stream < "$1" | sponge "$1"
fi
