#!/bin/bash
# Copy $1 into $2 and replace with pointers
set -e
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
warn-timeout "Destination files and directories, if present, will be overwritten."
crystalWorkdir="$(crystallize-getconf 'WorkDirectory')"
rsync -av --checksum --progress --no-i-r "$1" "$crystalWorkdir/"
rsync -av --checksum --progress --no-i-r "$1" "$crystalWorkdir/"
scache_store_files --replace "$crystalWorkdir/$(basename "$1")"
rsync -av --checksum --progress --no-i-r "$crystalWorkdir/$(basename "$1")" "$2/"
rsync -av --checksum --progress --no-i-r "$crystalWorkdir/$(basename "$1")" "$2/"
