#!/bin/bash
# Copy $1 into $2 and replace with pointers. $1 cannot be a directory.
set -e
set -x
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
if ! [ -f "$1" ]; then
    error-notify "Item must be a regular file."
    exit 1
fi
pointerTypeSignature="$(head -c 36 "$2/$1")"
destinationChecksum=""
if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
    destinationChecksum="$(tail -c +38 "$2/$1")"
    sourceChecksum="$(sha512sum < "$1" | awk '{print $1;}')"
    if [[ "$destinationChecksum" == "$sourceChecksum" ]]; then
        # The file is already present and pointerized, so exit without doing anything.
        exit 0
    fi
fi
crystalWorkdir="$(crystallize-getconf 'WorkDirectory')"
streamId="scache-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
crystalSubdir="$crystalWorkdir/$streamId"
mkdir -p "$crystalSubdir/$(dirname "$1")"
rsync -av --checksum --progress --no-i-r "$1" "$crystalSubdir/$1"
rsync -av --checksum --progress --no-i-r "$1" "$crystalSubdir/$1"
scache_store_files --replace "$crystalSubdir/$1"
rsync -av --checksum --progress --no-i-r "$crystalSubdir/$1" "$2/$1"
rsync -av --checksum --progress --no-i-r "$crystalSubdir/$1" "$2/$1"
rm -r "$crystalSubdir"
