#!/bin/bash
# Accepts a pointer as an argument, and returns a success status if the data corresponding to the pointer can be read. If it fails, it moves the pointer that failed validation aside.
set -e
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
# FIXME: The next line should not be necessary
source crystallize-bash_setup
echo "Started verifying stream cache database entry $knownHash."
crystalWorkdir=$(crystallize-getconf 'WorkDirectory')
knownHash="$(basename "$1")"
recoveredHash="$(scache_read_stream --disallow-hash-pointer < "$1" | sha512sum | awk '{print $1;}')"
if [[ "$knownHash" == "$recoveredHash" ]]; then
    echo "Verified stream cache database entry $knownHash."
    exit 0
fi
dbDir=/Ember\ Library/Futuramerlin\ Projects/Data/Stream\ Registry/Failed\ Fsck/
mkdir -p "$dbDir"
mv "$1" "$dbDir"
error-die "Error verifying stream cache database entry $knownHash!"
exit 1
