#!/bin/bash
# Verify that all hash pointers in the specified directory can be read correctly
set -e
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
find "$1" -type f -exec scache_verify_hashpointer 5 {} \;
