#!/bin/bash
source "$(which ember_bash_setup)" &> /dev/null

# Enroll the specified file(s) in the stream cache database
# Be VERY careful with the --replace option: it does not warn before acting!

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
set -e

scacheReplace=""
if [[ "$1" == "--replace" ]]; then
    scacheReplace="true"
    shift
fi
while [[ ! -z "$1" ]]; do
    echo "Items remaining to store: "
    echo "$@"
    fileToStash="$1"
    echo "Begun storing $fileToStash."
    if [ -f "$fileToStash" ]; then
        if [[ "$scacheReplace" == "true" ]]; then
            scache_store_stream --verbose < "$fileToStash"
            sha512sum < "$fileToStash" | awk '{print "'760fa662-89cf-4ebd-9664-150b7637ddd4\\n'"$1;}' | sponge "$fileToStash"
        else
            scache_store_stream --verbose < "$fileToStash"
        fi
    else
        if [ -d "$fileToStash" ]; then
            if [[ "$scacheReplace" == "true" ]]; then
                find "$fileToStash" -type f -exec scache_store_files --replace {} \;
            else
                find "$fileToStash" -type f -exec scache_store_files {} \;
            fi
        else
            warn "Skipping item $fileToStash: not a regular file or directory."
        fi
    fi
    echo "Done storing $fileToStash." || warn "Failed storing $fileToStash!"
    shift
done
#printf "\033c"
echo "Done storing all items."
