#!/bin/bash
source "$(which ember_bash_setup)" &> /dev/null

# Copy $1 into $2 and replace with pointers. $1 cannot be a directory.

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
trap 'error-die "${BASH_SOURCE}" "${LINENO}"' ERR
#set -x

if ! [ -f "$1" ]; then
    error-notify "Item must be a regular file."
    exit 1
fi
if [ -f "$2/$1" ]; then
    pointerTypeSignature="$(head -c 36 "$2/$1")"
    destinationChecksum=""
    if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
        destinationChecksum="$(tail -c +38 "$2/$1")"
        sourceChecksum="$(sha512sum < "$1" | awk '{print $1;}')"
        if [[ "$destinationChecksum" == "$sourceChecksum" ]]; then
            # The file is already present and pointerized, so exit without doing anything.
            echo "(Nothing done for $1.)"
            exit 0
        fi
    fi
fi
crystalWorkdir="$(crystallize-getconf 'WorkDirectory')"
streamId="scache-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
crystalSubdir="$crystalWorkdir/$streamId"
targetDirName="$(dirname "$1")"
mkdir -p "$crystalSubdir/$targetDirName"
rsync -a --checksum --no-i-r "$1" "$crystalSubdir/$targetDirName/"
rsync -a --checksum --no-i-r "$1" "$crystalSubdir/$targetDirName/"
scache_store_files --replace "$crystalSubdir/$1"
mkdir -p "$2/$targetDirName"
rsync -a --checksum --no-i-r "$crystalSubdir/$1" "$2/$targetDirName/"
rsync -a --checksum --no-i-r "$crystalSubdir/$1" "$2/$targetDirName/"
rm -r "$crystalSubdir"
