#!/bin/bash
# Accepts a pointer as an argument, and replaces the file with the pointer's contents if it does not match its hash.
# Internal use only.
set -e
knownHash="$(basename "$1")"
recoveredHash="$(sha512sum "$1" | awk '{print $1;}')"
if [[ "$knownHash" != "$recoveredHash" ]]; then
    echo "Begun backup operation for $1"
    scache_read_stream < "$1" | sponge "$1"
    echo -n "Finished backup operation for $1 (backup occupies "
else
    echo "(Backup for $1 already completed, occupying "
fi
echo -n "$(du -bsh "$1")"
echo ")"
