#!/bin/bash
# Verify that all entries in the stream database can be read correctly
set -e
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
dbDir=/Ember\ Library/Futuramerlin\ Projects/Data/Stream\ Registry
find "$dbDir" -type f -not -path "$dbDir/Failed Fsck/*" -not -path "$dbDir/LocalStore/*" -exec scache_verify_entry 5 {} \;
