#!/bin/bash
source "$(which ember_bash_setup)" &> /dev/null

# Verify that all hash pointers in the specified directory can be read correctly

runAsRootAndSetE
find "$1" -type f -exec scache_verify_hashpointer 5 {} \;
