#!/bin/bash
source "$(which ember_bash_setup)" &> /dev/null

# Copy $1 into $2 and resolve pointers

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
trap 'error-die "${BASH_SOURCE}" "${LINENO}"' ERR

scache_copy_read "$@"
