#!/bin/bash
# Copy $1 into $2 and replace with pointers, skipping existing
set -e
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
find "$1" -not -type f -exec rsync -lptgoD --checksum {} "$2/" \;
find "$1" -type f -exec scachei_copy_write {} "$2" \;
