#!/bin/bash
# Copy $1 into $2 and replace with pointers, skipping existing
set -e
set -x
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
find "$1" -not -type f -exec rsync -lptgoD --checksum {} "$2/" \;
find "$1" -type f -exec scachei_copy_write {} "$2" \;
rsync -av --progress --ignore-existing --no-i-r "$1" "$2/"
find "$2/$1" -type d -empty -exec touch {}/.keep \;
find "$2/$1" -type f -exec scachei_replace_conditional {} \;
