#!/bin/bash
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
crystalWorkdir=$(crystallize-getconf 'WorkDirectory')
(
    cd "$crystalWorkdir"
    streamId="smallify-stream-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
    sponge "$streamId.tmp"
    smallify "$streamId.tmp" > "$streamId.tmp.sstream-stdout" 2> "$streamId.tmp.sstream-stderr"
    echo "a5e2f296-3085-49c0-8f48-24ea436b7a8b"
    tar -c -P -S --format pax "$streamId.tmp.crystal" ".$streamId.tmp.crystal-data" "$streamId.tmp.sstream-stdout" "$streamId.tmp.sstream-stderr" | xz -k -C sha256 -T 0 --lzma2=preset=1 --stdout -
)
