#!/bin/bash
# Smallify the specified file(s) using the cache database
set -e
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
while [[ ! -z $1 ]]; do
    echo "Items remaining to smallify: "
    echo "$@"
    fileToStash="$1"
    echo "Begun smallifying $fileToStash."
    if [ -f "$fileToStash" ]; then
        sstream-precache "$fileToStash"
        smallify-files "$fileToStash"
    else
        if [ -d "$fileToStash" ]; then
            find "$fileToStash" -type f -exec sstream-precache {} \;
            find "$fileToStash" -type f -exec smallify-files {} \;
        else
            echo "Warning: Skipping item $fileToStash (not a regular file or directory)"
        fi
    fi
    echo "Done smallifying $fileToStash."
    shift
done
printf "\033c"
echo "Done smallifying all items."
