#!/bin/bash
# smallify

# See crystallize for requirements.

#Usage: smallify <crystal-directory>

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"

#Script should exit if any operation fails.
set -e

shopt -s extglob

crystallize --leave-pointer "$@"
