#!/bin/bash
source "$(which ember_bash_setup)" &> /dev/null

# Copy $1 into $2 and replace with pointers. $1 cannot be a directory.

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
#set -x

if [ "$1" == "--no-verify" ]; then
    echo "(Not verifying pointers.)"
    sregNoVerify=true
    shift
fi
if ! [ -f "$1" ]; then
    error-notify "Item must be a regular file."
    exit 1
fi
fsckStatusFile="$3"
if [ -n "$fsckStatusFile" ]; then
    numberExpected="$(<"$fsckStatusFile")"
    numberProcessedFile="$fsckStatusFile.done"
    if ! [ -f "$numberProcessedFile" ]; then
        numberProcessed="1"
    else
        numberProcessed="$(<"$numberProcessedFile")"
        numberProcessed=$(( numberProcessed + 1 ))
    fi
    echo "$numberProcessed" > "$numberProcessedFile"
    if [[ "$numberExpected" == "0" ]]; then
        numberExpected="-1"
    fi
    numberProcessedPercentage="$(printf "%.3f\n" "$(bc -l <<< "($numberProcessed / $numberExpected) * 100")")"
    echo "Copying item $1: #$numberProcessed of $numberExpected ($numberProcessedPercentage%)"
fi
destinationRootLength="$4"
targetLength=${#1}
destinationName="$2/${1:destinationRootLength:targetLength}"
echo "$destinationRootLength - $targetLength - $destinationName"
if [ -f "$destinationName" ]; then
    pointerTypeSignature="$(head -c 36 "$destinationName")"
    destinationChecksum=""
    hasEncounteredError="0"
    if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
        trap 'warn "A nonfatal error was reported on ${BASH_SOURCE} line ${LINENO}."; hasEncounteredError="1"' ERR
        assumePointerDbEntryFileExists="true"
        if [[ "$sregNoVerify" == "true" ]]; then
            destinationChecksum="$(tail -c +38 "$destinationName" | head -c 129)"
            pointerDbEntryFile="$EmberLibrary/Futuramerlin Projects/Data/Stream Registry/${destinationChecksum:0:1}/${destinationChecksum:1:1}/${destinationChecksum:2:1}/$destinationChecksum"
            if ! [[ -e "$pointerDbEntryFile" ]]; then
                assumePointerDbEntryFileExists="false"
            fi
        else
            destinationChecksum="$(sreg_read_stream < "$destinationName" | sha512sum | awk '{print $1;}')"
        fi
        sourceChecksum="$(sha512sum < "$1" | awk '{print $1;}')"
        if [[ "$destinationChecksum" == "$sourceChecksum" && "$hasEncounteredError" == "0" && "$assumePointerDbEntryFileExists" == "true" ]]; then
            # The file is already present, pointerized, and readable, so exit without doing anything.
            echo "(Nothing done for $1.)"
            exit 0
        else
            warn "(Destination pointer $destinationName could not be read or did not match source checksum; removing and recreating.)"
            cat "$destinationName"
            rm "$destinationName"
        fi
    fi
fi
trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
crystalWorkdir="$(crystallize-getconf 'WorkDirectory')"
streamId="sreg-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
crystalSubdir="$crystalWorkdir/$streamId"
mkdir -p "$crystalSubdir"
rsync -a --checksum --no-i-r "$1" "$crystalSubdir/"
sreg_store_files --replace "$crystalSubdir/$(basename "$1")"
rsync -a --checksum --no-i-r "$crystalSubdir/$(basename "$1")" "$destinationName"
rm -r "$crystalSubdir"
