#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

if [[ -n "$1" ]]; then
    if [[ -d "$1" ]]; then
        cd "$1" || die "Could not cd to specified directory!"
    else
        cd "$(dirname "$1")" || die "Could not cd to directory of specified path!"
    fi
fi

reportResult() {
    print "$1"
    exit 0
}

while [[ "$(readlink -e .)" != "/" ]]; do
    [[ -d ".sreg" ]] && reportResult "$(readlink -e .sreg)"
    cd .. || die "Could not cd to enclosing directory!"
done

reportResult "${EmberLibrary:?}/Futuramerlin Projects/Data/Stream Registry/"
