#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

sregDir=""
if [[ "$1" == "--sreg-dir" ]]; then
    shift
    sregDir="$1"
    shift
fi
sregDir="$(sregi_find_dir --sreg-dir "$sregDir" --full-check)"

dbDir="$sregDir"
backupDir="$1"
rsync -av --checksum --progress --no-i-r --ignore-existing "$dbDir"/ "$backupDir"
find "$backupDir" -type f -exec sregi_file_backup --sreg-dir "$sregDir" {} \;

if [[ -e "$failCheckFile" ]]; then
    die "An invocation of sregi_file_backup (called from $0) failed with the message \"$(<"$failCheckFile")\"!"
fi

rsync -av --checksum --progress --no-i-r --ignore-existing "$dbDir"/ "$backupDir"
find "$backupDir" -type f -exec sregi_verify_backup {} \;

if [[ -e "$failCheckFile" ]]; then
    die "An invocation of sregi_verify_backup (called from $0) failed with the message \"$(<"$failCheckFile")\"!"
fi
