#!/bin/bash
source "$(which ember_bash_setup)" &> /dev/null

# Make a clone of the stream database where the bodies of the streams are stored instead of the pointers.

trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR

dbDir=/Ember\ Library/Futuramerlin\ Projects/Data/Stream\ Registry
backupDir=/Ember\ Library/Futuramerlin\ Projects/Data/Stream\ Backups
rsync -av --checksum --progress --no-i-r --ignore-existing "$dbDir"/ "$backupDir"
find "$backupDir" -type f -exec scachei_verify_backup {} \;
rsync -av --checksum --progress --no-i-r --ignore-existing "$dbDir"/ "$backupDir"
find "$backupDir" -type f -exec scachei_file_backup {} \;
