#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

[[ -n "$1" ]] && cd "$1"

reportResult() {
    print "$1"
    exit 0
}

while [[ "$(readlink -e .)" != "/" ]]; do
    [[ -d ".sreg" ]] && reportResult "$(readlink -e .sreg)"
    cd ..
done

reportResult "${EmberLibrary:?}/Futuramerlin Projects/Data/Stream Registry/"
