#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"

sregDir=""
if [[ "$1" == "--sreg-dir" ]]; then
    shift
    sregDir="$1"
    shift
fi
sregDir="$(sregi_find_dir --sreg-dir "$sregDir" --full-check)"

outFile=""
if [[ "$1" == "--output-file" ]]; then
    shift
    outFile="$1"
    shift
fi

finish() {
    (
        cd "/${crystalWorkdir:?}/" || die
        if [[ -e ".${streamId:?}" ]]; then
            rm -r ".${streamId:?}"
        fi
    )
}
trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."; finish; exit 1' ERR

dbDir="$sregDir"
crystalWorkdir="$(crystallize-getconf WorkDirectory)"
# Don't change the value of streamId: it would break compatibility with existing pointers.
streamId="scache-$(date-uuid)"
mkdir -p "$crystalWorkdir/.$streamId/$streamId"
(
    cd "$crystalWorkdir/.$streamId/$streamId" || die
    sponge "$streamId.tmp"
    streamLength="$(stat --printf='%s\n' "$streamId.tmp")"
    # Calculate hash
    if [[ "$1" == "--assume-checksum" ]]; then
        shift
        hashFull="$1"
        shift
    else
        hashFull="$(sha512sum < "$streamId.tmp" | awk '{print $1;}')"
    fi
    sregStoreStreamVerbose=""
    if [[ "$1" == "--verbose" ]]; then
        sregStoreStreamVerbose="true"
    fi
    inputPointerTypeSignature=""
    if ! [[ "$(wc -c < "$streamId.tmp")" -lt 166 ]]; then
        inputPointerTypeSignature="$(head -c 36 "$streamId.tmp")"
    fi
    if [[ "$inputPointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]] || # Hash pointer
        [[ "$inputPointerTypeSignature" == "a5e2f296-3085-49c0-8f48-24ea436b7a8b" ]] || # Standard remote pointer
        [[ "$inputPointerTypeSignature" == "c39f8657-384b-438b-a5a2-eece17147589" ]] || # LocalStore pointer
        [[ "$inputPointerTypeSignature" == "2fae2004-94bb-4aa8-a01a-fc44298efc2c" ]] || # Remote pack pointer
        [[ "$inputPointerTypeSignature" == "209fcfdf-d1ad-4345-8ef7-1fdc2d583d49" ]] || # Remote pack pointer, with pointer data in the pointer
        [[ "$inputPointerTypeSignature" == "45baff46-8db7-46f6-aad9-de5f713b02fe" ]] # URL pointer
    then
        die "The input stream is a sreg pointer, and cannot be safely stored."
    fi
    if [[ -n "$outFile" ]]; then
        if [[ -f "$outFile" ]]; then
            pointerTypeSignature=""
            if ! [[ "$(wc -c < "$outFile")" -lt 166 ]]; then
                pointerTypeSignature="$(head -c 36 "$outFile")"
            fi
            if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
                # The file is a hash pointer. This is fine: Check if the output-file is already a pointer for this file, and if not, continue nomally.
                outFileHashFull="$(sregi_hash_from_file "$outFile")"
                if [[ "$hashFull" == "$outFileHashFull" ]]; then
                    # Basic sanity check for existing pointer
                    sregi_hashpointer_sane --sreg-dir "$sregDir" "$outFile"
                    # Previous command exited OK, so the pointer already there is good to go.
                    finish; exit 0
                fi
                # Continue normally: the hash for the existing pointer at output-file is different from the file being stored.
                true
            elif [[ "$pointerTypeSignature" == "a5e2f296-3085-49c0-8f48-24ea436b7a8b" ]] || # Standard remote pointer
                [[ "$pointerTypeSignature" == "c39f8657-384b-438b-a5a2-eece17147589" ]] || # LocalStore pointer
                [[ "$pointerTypeSignature" == "2fae2004-94bb-4aa8-a01a-fc44298efc2c" ]] || # Remote pack pointer
                [[ "$pointerTypeSignature" == "209fcfdf-d1ad-4345-8ef7-1fdc2d583d49" ]] || # Remote pack pointer, with pointer data in the pointer
                [[ "$pointerTypeSignature" == "45baff46-8db7-46f6-aad9-de5f713b02fe" ]] # URL pointer
            then
                # The file is a stream pointer, but not a hash pointer.
                die "Refusing to overwrite non-hashpointer stream pointer."
            else
                # The file is a normal file. Either it's the same, in which case do nothing, or it's different, in which case overwrite it.
                outFileHash="$(sha512sum < "$outFile" | awk '{print $1;}')"
                if [[ "$hashFull" == "$outFileHash" ]]; then
                    finish; exit 0
                else
                    mv "$streamId.tmp" "$outFileHash"
                    finish; exit 0
                fi
            fi
        fi
    fi
    # Upload a pack of the LocalStore items if there are enough, and update the pointers accordingly.
    if ! [[ -e "$crystalWorkdir/.LocalStoreCache/" ]]; then
        localstorecache_init "$crystalWorkdir/.LocalStoreCache/" 5000000000
    fi
    if ! [[ -e "$dbDir"/LocalStore ]]; then
        mkdir -p "$dbDir"/LocalStore
    fi
    localStoreSize="$(du -sb "$dbDir"/LocalStore | awk '{print $1;}')"
    if [[ "$localStoreSize" -gt 100000000 ]]; then
        if [[ "$localStoreSize" -gt 300000000 ]] && [[ -e "$dbDir"/.LocalStore.lock ]]; then
            die "LocalStore is larger than expected, and lock file is present. Has a previous invocation of sreg_flush_localstore crashed? If so, manually remove $dbDir/.LocalStore.lock and re-run sreg_flush_localstore... (It's possible that sreg_flush_localstore is still running, though.)"
        fi
        if [[ "$sregStoreStreamVerbose" != "true" ]]; then
            sreg_flush_localstore --sreg-dir "$sregDir" > /dev/null
        else
            sreg_flush_localstore --sreg-dir "$sregDir" >&2
        fi
    fi
    hashA="${hashFull:0:1}"
    hashB="${hashFull:1:1}"
    hashC="${hashFull:2:1}"
    hashDir="$dbDir/$hashA/$hashB/$hashC"
    mkdir -p "$hashDir"
    dbFilePath="$hashDir/$hashFull"
    tmpFilePath="$streamId.tmp.stored"
    streamSize="$(du -sb "$streamId.tmp" | awk '{print $1;}')"
    if [[ "$streamSize" -gt 20000000 ]]; then
        useLocalStore="false"
    else
        useLocalStore="true"
        localStoreDir="$dbDir/LocalStore/$hashA/$hashB/$hashC"
        mkdir -p "$localStoreDir"
        localStoreFilePath="$localStoreDir/$hashFull"
    fi
    sanityCheckPassed=""
    if [[ -f "$dbFilePath" ]]; then
        sanityCheckPassed="0"
        knownChecksum="$hashFull"
        if sregi_available_by_hash --sreg-dir "$sregDir" "$knownChecksum" &> /dev/null; then
            # This previously next checked whether the existing pointer could be restored.
            # It doesn't do that now, because there should be no need:
            # we should assume that the basic sanity check is sufficient, and
            # rely on the user regularly running sreg_fsck --skip-cache (because
            # the errors that this would catch are only a select few (the ones
            # being stored again) of the possible streams that could have this
            # class of error).
            sanityCheckPassed="1"
        else
            # Item failed a basic sanity check, so it can pretty safely be removed and recreated, because it would presumably be found failed by that same basic sanity check in the course of general maintenance.
            rm "$dbFilePath"
        fi
    fi
    if [[ -f "$dbFilePath" ]] && [[ "$sanityCheckPassed" != "1" ]]; then
        die "Database entry did not pass sanity check, but still exists! This should never happen."
    fi
    if [[ ! -f "$dbFilePath" ]]; then
        # Item not available in cache, so add it (c39... is the LocalStore pointer type signature; a5e... is the remote type signature)
        pointerTypeSignature="c39f8657-384b-438b-a5a2-eece17147589"
        if [[ "$useLocalStore" != "true" ]]; then
            if [[ "$sregStoreStreamVerbose" == "true" ]]; then
                crystallize --leave-locked --passphrase "$(sregi_get_passphrase "$sregDir")" --leave-pointer "$streamId.tmp" > /dev/null
            else
                crystallize --leave-locked --passphrase "$(sregi_get_passphrase "$sregDir")" --leave-pointer "$streamId.tmp" &> /dev/null
            fi
            pointerTypeSignature="a5e2f296-3085-49c0-8f48-24ea436b7a8b"
        fi
        echo "$pointerTypeSignature" > "$tmpFilePath"
        echo "$hashFull" >> "$tmpFilePath"
        echo "$streamLength" > "$tmpFilePath.length"
        if [[ "$useLocalStore" != "true" ]]; then
            tar -c -P -S --format pax "$streamId.tmp.crystal" ".$streamId.tmp.crystal-data" > "$streamId.nonbundle.pointer.tar"
            [[ "$(xxd "$streamId.nonbundle.pointer.tar" | head -c 12)" == "00000000: 00" ]] && { mkdir -p "$(crystallize-getconf WorkDirectory)/.CorruptSregTarFileInfo/$streamId/"; rsync -a "$streamId.LocalStore.crystal" ".$streamId.LocalStore.crystal-data" "$streamId.nonbundle.pointer.tar" "$(crystallize-getconf WorkDirectory)/.CorruptSregTarFileInfo/$streamId/"; die "Pointer pax was corrupt!"; }
            checkedxz --quiet - -k -C sha256 -T 0 -9 -e < "$streamId.nonbundle.pointer.tar" >> "$tmpFilePath"
        else
            checkedxz --quiet "$streamId.tmp" --stdout -k -C sha256 -T 0 -9 -e > "$localStoreFilePath"
        fi
        trap finish EXIT
        sregi_verify_entry --lock-override --sreg-dir "$sregDir" "$tmpFilePath" > /dev/null || die "Failed saving stream: stored stream could not be read!"
        trap - EXIT
        mv "$tmpFilePath" "$dbFilePath" || die "Could not move pointer into place!"
    fi
    # Output the finished hashpointer
    if [[ -n "$outFile" ]]; then
        printf '%s\n%s\n' "760fa662-89cf-4ebd-9664-150b7637ddd4" "$hashFull" > "$outFile"
        echo "$streamLength" >> "$outFile"
    else
        printf '%s\n%s\n' "760fa662-89cf-4ebd-9664-150b7637ddd4" "$hashFull"
        echo "$streamLength"
    fi
    finish
    if [[ -e "${streamId:?}.tmp" ]]; then
        rm "${streamId:?}.tmp"
    fi
    if [[ -e "${streamId:?}.tmp.crystal" ]]; then
        rm "${streamId:?}.tmp.crystal"
    fi
)
