#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

useCustomPassphrase="false"
customPassphrase=""
if [[ "$1" == "--passphrase" ]]; then
    useCustomPassphrase="true"
    shift
    customPassphrase="$1"
    shift
fi

addToGitignore="true"
if [[ "$1" == "--no-gitignore" ]]; then
    addToGitignore="false"
    shift
fi

directory="."
[[ -n "$1" ]] && directory="$1"

mkdir -p "$directory/.sreg"
echo "$(readlink -f "$directory")" > "$directory/.sreg/.sreg.root"
if [[ "$addToGitignore" == "true" ]]; then
    echo ".sreg/LocalStore" >> "$directory/.gitignore"
fi
if [[ "$useCustomPassphrase" == "true" ]]; then
    print "$customPassphrase" > "$directory/.sreg/.sreg.passphrase"
fi
