#!/bin/bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

# Resolve pointers within the specified file(s)

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR

while [[ ! -z "$1" ]]; do
    echo "Items remaining to resolve: "
    echo "$@"
    fileToResolve="$1"
    echo "Begun resolving $fileToResolve."
    if [ -f "$fileToResolve" ]; then
        sreg_read_stream < "$fileToResolve" | sponge "$fileToResolve" || echo "(Note: ignoring failed read of $fileToResolve)"
    else
        if [ -d "$fileToResolve" ]; then
            find "$fileToResolve" -type f -exec sreg_read_files {} \;
        else
            warn "Skipping item $fileToResolve: not a regular file or directory."
        fi
    fi
    echo "Done resolving $fileToResolve." || warn "Failed resolving $fileToResolve!"
    shift
done
#printf "\033c"
echo "Done resolving all items."
