#!/bin/bash
source "$(which ember_bash_setup)" &> /dev/null

# Accepts an integer and a pointer as an argument, and returns a success status if the data corresponding to the pointer can be read. If it fails, it moves the pointer that failed validation aside. The integer first argument is the number of times to retry if the retrieval fails.

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR

pointerTypeSignature="$(head -c 36 "$2")"
knownChecksum=""
if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
    knownChecksum="$(tail -c +38 "$2")"
    recoveredChecksum="$(scache_read_stream < "$2" | sha512sum | awk '{print $1;}')"
    if [[ "$knownChecksum" != "$recoveredChecksum" ]]; then
        set +e
        mv "$2" "$2.CORRUPTED-HASHPOINTER"
        set -e
        error-die "Item $2 did not match the stored checksum!"
    fi
fi
