#!/usr/bin/env emberPlatformResolver-bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

failCheckFile="$1"
if [[ -e "$failCheckFile" ]]; then
    die "A previous invocation of $0 failed with the message \"$(<"$failCheckFile")\"! Aborting."
else
    echo "$0 running in $(readlink -f "$(pwd)") with the arguments $*" > "$failCheckFile" || echo "$0 running in an unknown directory with the arguments $*" > "$failCheckFile"
fi
shift
success() {
    rm -f "${failCheckFile:?}"
    exit 0
}

sregDir=""
if [[ "$1" == "--sreg-dir" ]]; then
    shift
    sregDir="$1"
    shift
fi
sregDir="$(sregi_find_dir --sreg-dir "$sregDir")"

knownHash="$(basename "$1")"
recoveredHash="$(sha512sum < "$1" | awk '{print $1;}')"
if [[ "$knownHash" != "$recoveredHash" ]]; then
    echo "Begun backup operation for $1"
    # FIXME: This shellcheck directive is only needed for outdated shellcheck versions. Once CodeClimate's shellcheck gets updated (which probably means when Debian stable updates shellcheck), it can be removed.
    # shellcheck disable=SC2094
    sreg_read_stream --sreg-dir "$sregDir" < "$1" | sponge "$1"
    echo -n "Finished backup operation for $1 (backup occupies "
else
    echo -n "(Backup for $1 already completed, occupying "
fi
echo -n "$(du -bsh "$1" | awk '{print $1;}')"
echo ")"

success
