#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"

finish() {
    trap - ERR
    (
    crystalWorkdir="$(crystallize-getconf WorkDirectory)"
    cd "/${crystalWorkdir:?}/" || die
    if [[ -n "$streamId" ]]; then
        if [[ -e "/$crystalWorkdir/${streamId:?}" ]]; then
            rm -r "/$crystalWorkdir/${streamId:?}"
        fi
    fi
    )
    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} while finishing sregi_copy_write."' ERR
}
trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; finish; exit 1' ERR
trap finish EXIT

if [[ "$1" == "--no-verify" ]]; then
    #echo "(Not verifying pointers.)"
    sregNoVerify=true
    shift
fi
#echo "$@"
if ! [[ -f "$1" ]]; then
    error-notify "Item must be a regular file."
    exit 1
fi
fsckStatusFile="$3"
if [[ -n "$fsckStatusFile" ]]; then
    numberExpected="$(<"$fsckStatusFile")"
    numberProcessedFile="$fsckStatusFile.done"
    if ! [[ -f "$numberProcessedFile" ]]; then
        numberProcessed="1"
    else
        numberProcessed="$(<"$numberProcessedFile")"
        numberProcessed=$(( numberProcessed + 1 ))
    fi
    echo "$numberProcessed" > "$numberProcessedFile"
    if [[ "$numberExpected" == "0" ]]; then
        numberExpected="-1"
    fi
    numberProcessedPercentage="$(printf "%.3f\\n" "$(bc -l <<< "($numberProcessed / $numberExpected) * 100")")"
    echo "Copying item $1: #$numberProcessed of $numberExpected ($numberProcessedPercentage%)"
else
    echo "Copying item $1."
fi
# FIXME: This shellcheck directive is only needed for outdated shellcheck versions. Once CodeClimate's shellcheck gets updated (which probably means when Debian stable updates shellcheck), it can be removed.
# shellcheck disable=SC2034
destinationRootLength="$4"
# FIXME: This shellcheck directive is only needed for outdated shellcheck versions. Once CodeClimate's shellcheck gets updated (which probably means when Debian stable updates shellcheck), it can be removed.
# shellcheck disable=SC2034
sourceNameReplaced="${1/%.git/.git.686fc528-0e8e-4724-91bb-c103cdcdd592}"
sourceNameReplaced="${sourceNameReplaced//\/.git\//\/.git.686fc528-0e8e-4724-91bb-c103cdcdd592\/}"
targetLength=${#sourceNameReplaced}
#echo "$destinationRootLength - $targetLength"
destinationName="$2/${sourceNameReplaced:destinationRootLength:targetLength}"
#echo "$destinationName"
sourceChecksum="$(sha512sum < "$1" | awk '{print $1;}')"
if [[ -f "$destinationName" ]]; then
    pointerTypeSignature="$(head -c 36 "$destinationName")"
    destinationChecksum=""
    hasEncounteredError="0"
    if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
        trap 'warn "A nonfatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; hasEncounteredError="1"' ERR
        assumePointerDbEntryFileExists="true"
        if [[ "$sregNoVerify" == "true" ]]; then
            destinationChecksum="$(tail -c +38 "$destinationName" | head -c 129)"
            pointerDbEntryFile="${EmberLibrary:?}/Futuramerlin Projects/Data/Stream Registry/${destinationChecksum:0:1}/${destinationChecksum:1:1}/${destinationChecksum:2:1}/$destinationChecksum"
            if ! [[ -e "$pointerDbEntryFile" ]]; then
                assumePointerDbEntryFileExists="false"
            else
                innerPointerTypeSignature="$(head -c 36 "$pointerDbEntryFile")"
                if [[ "$innerPointerTypeSignature" == "c39f8657-384b-438b-a5a2-eece17147589" ]]; then
                    if ! [[ -e "${EmberLibrary:?}/Futuramerlin Projects/Data/Stream Registry/LocalStore/${destinationChecksum:0:1}/${destinationChecksum:1:1}/${destinationChecksum:2:1}/$destinationChecksum" ]]; then
                        assumePointerDbEntryFileExists="false"
                    fi
                fi
            fi
        else
            destinationChecksum="$(tail -c +38 "$destinationName" | head -c 129)"
            sreg_read_stream < "$destinationName" > /dev/null || hasEncounteredError="1"
        fi
        if [[ "$destinationChecksum" == "$sourceChecksum" && "$hasEncounteredError" == "0" && "$assumePointerDbEntryFileExists" == "true" ]]; then
            # The file is already present, pointerized, and readable, so exit without doing anything.
            echo "(Nothing done for $1.)"
            exit 0
        else
            warn "(Note: Destination pointer $destinationName did not match source checksum or could not be read: the source file has probably been changed. Removing and recreating.)"
            # cat "$destinationName"
            rm "${destinationName:?}"
        fi
    else
        if [[ "$pointerTypeSignature" != "a5e2f296-3085-49c0-8f48-24ea436b7a8b" ]] && # Standard remote pointer
            [[ "$pointerTypeSignature" != "c39f8657-384b-438b-a5a2-eece17147589" ]] && # LocalStore pointer
            [[ "$pointerTypeSignature" != "209fcfdf-d1ad-4345-8ef7-1fdc2d583d49" ]] && # Remote pack pointer
            [[ "$pointerTypeSignature" != "2fae2004-94bb-4aa8-a01a-fc44298efc2c" ]] && # Also remote pack pointer
            [[ "$pointerTypeSignature" != "209fcfdf-d1ad-4345-8ef7-1fdc2d583d49" ]] && # Pack pointer data is in the pointer
            [[ "$pointerTypeSignature" != "760fa662-89cf-4ebd-9664-150b7637ddd4" ]] # Hash pointer
        then
            if [[ "$sourceChecksum" == "$(sha512sum < "$destinationName" | awk '{print $1;}')" ]]; then
                echo "(Skipping matching normal file $destinationName)"
            fi
        fi
    fi
fi
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
crystalWorkdir="$(crystallize-getconf WorkDirectory)"
streamId="sreg-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
crystalSubdir="$crystalWorkdir/$streamId"
mkdir -p "$crystalSubdir"
rsync -a --checksum --no-i-r "$1" "$crystalSubdir/"
setVariableToCommandOutput "basename" "embasename" "$1"
fileToStash="$crystalSubdir/${basename:?}"
if [[ -f "$fileToStash" ]]; then
    sreg_store_stream --assume-checksum "$sourceChecksum" < "$fileToStash" | sponge "$fileToStash"
else
    die "Skipping item $fileToStash: not a regular file."
fi
mkdir -p "$(dirname "$destinationName")"
rsync -a --checksum --no-i-r "$fileToStash" "$destinationName"
# a+r gives (a)ll users (r)ead permission
chmod a+r "$destinationName"
rm -r "${crystalSubdir:?}"
if [[ -e "${streamId:?}" ]]; then
    rm -r "${streamId:?}"
fi

finish
