#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

reportDefault() {
    crystallize-getconf Passphrase
}

sregDir="$1"

if [[ -e "$sregDir"/.sreg/passphrase ]]; then
    cat "$sregDir"/.sreg/passphrase
else
    
fi
