#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

sregDir=""
if [[ "$1" == "--sreg-dir" ]]; then
    shift
    sregDir="$1"
    shift
fi
sregDir="$(sregi_find_dir --sreg-dir "$sregDir" --full-check)"

iaUrl="$1"
isIaUrl "$iaUrl" || die "The value specified does not appear to be an Internet Archive URL!"
temp="$(tempFile)"
sregi_url_pointer "$iaUrl" > "$temp"
ptrHash="$(sregi_hash_from_file "$temp")"
