#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

sregDir="$1"

if [[ -e "$sregDir"/passphrase ]] && [[ -n "$sregDir" ]]; then
    cat "$sregDir"/passphrase
else
    crystallize-getconf Passphrase
fi
