#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"

sregDir=""
if [[ "$1" == "--sreg-dir" ]]; then
    shift
    sregDir="$1"
    shift
fi
sregDir="$(sregi_find_dir --sreg-dir "$sregDir" --full-check)"

finish() {
    trap - ERR
    if [[ -e "$crystalWorkdir/${fsckId:?}" ]]; then
        rm -r "$crystalWorkdir/${fsckId:?}"
    fi
    if [[ -e "/tmp/${fsckId:?}" ]]; then
        rm -r "/tmp/${fsckId:?}"
    fi
    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} while finishing sreg_folder_check."' ERR
}
trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; finish; exit 1' ERR
trap finish EXIT

sregVerify=""
if [[ "$1" == "--verify" ]]; then
    sregVerify="--verify"
    shift
fi

dropUnused="false"
if [[ "$1" == "--drop-unused" ]]; then
    dropUnused="true"
    shift
fi

folderToCheck="$1"
if [[ -z "$folderToCheck" ]]; then
    folderToCheck="."
fi

echo "Counting items..."
crystalWorkdir="$(crystallize-getconf WorkDirectory)"
fsckId="sreg_folder_check-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
mkdir -p "$crystalWorkdir/${fsckId:?}"
mkdir -p "/tmp/${fsckId:?}"
fsckStatusFile="/tmp/$fsckId/.sreg_folder_check.status"
fsckIdList="/tmp/$fsckId/.sreg_folder_check.idlist"
find "$folderToCheck" -type f -printf '.' | wc -c > "$fsckStatusFile"
bpid="$$"
find "$folderToCheck" -type f \( -exec sregi_hashpointer_sane {} "$fsckIdList" "$fsckStatusFile" "$sregVerify" \; -or -exec kill "-$bpid" \; \)

if [[ "$dropUnused" == "false" ]]; then
    finish
    exit 0
fi

sregDir="$(sregi_find_dir)"
find "$sregDir" -not -path "$sregDir/Unused Pointers/*" -type f -printf '.' | wc -c > "$fsckStatusFile"
echo "0" > "$fsckStatusFile.done"

find "$sregDir" -not -path "$sregDir/Unused Pointers/*" -type f \( -exec sregi_drop_single_unused {} "$fsckIdList" "$fsckStatusFile" \; -or -exec kill "-$bpid" \; \)

finish
