#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
function finish() {
    if [[ -e "${crystalWorkdir:?}/${fsckId:?}" ]]; then
        rm -r "${crystalWorkdir:?}/${fsckId:?}"
    fi
}
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
trap finish EXIT

echo "Counting items..."
crystalWorkdir="$(crystallize-getconf WorkDirectory)"
fsckId="sreg_fsck-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
mkdir -p "$crystalWorkdir/${fsckId:?}"
mkdir -p "/tmp/${fsckId:?}"
fsckStatusFile="/tmp/$fsckId/.sreg_fsck.status"
dbDir="${EmberLibrary:?}"/Futuramerlin\ Projects/Data/Stream\ Registry
find "$dbDir" -type f -not -path "$dbDir/Failed Fsck/*" -not -path "$dbDir/LocalStore/*" -not -path "$dbDir/Packs/*" -printf '.' | wc -c > "$fsckStatusFile"
rm -f "$fsckStatusFile.failed"
bpid="$$"
find "$dbDir" -type f -not -path "$dbDir/Failed Fsck/*" -not -path "$dbDir/LocalStore/*" -not -path "$dbDir/Packs/*" \( -exec sregi_verify_entry {} "$fsckStatusFile" \; -or -exec kill "-$bpid" \; \)
[[ -e "$fsckStatusFile.failed" ]] && die "Failed verifying entry! Aborted."
echo "Done all items."
finish
