#!/bin/bash
source "$(which ember_bash_setup)" &> /dev/null

# Replace files with pointers, if not already a pointer.

[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR

if ! [ -f "$1" ]; then
    error-notify "Item must be a regular file."
    exit 1
fi
if [[ "$(head -c 36 "$1")" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
    if [[ sreg_verify_entry "$1" ]]; then
        exit 0
    else
        warn "Entry $1 failed verification! Entry contents: "
        cat "$1"
        echo "Removing pointer; it should be re-created on the next sync."
        rm "$1"
        exit 1
    fi
fi
sreg_store_files --replace "$1"
