#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

useCustomPassphrase="false"
customPassphrase=""
if [[ "$1" == "--passphrase" ]]; then
    useCustomPassphrase="true"
    shift
    customPassphrase="$1"
    shift
fi

directory="."
[[ -n "$1" ]] && directory="$1"

mkdir -p "$directory/.sreg"
touch "$directory/.sreg/.sreg.conf"
[[ useCustomPassphrase == "true" ]] && print "$customPassphrase" > "$directory/.sreg/.sreg.conf"
