#!/bin/bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

((EUID)) && exec sudo -- "$0" "$@"
trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
#set -x

fsckStatusFile="$2"
knownHash="$(tail -c +38 "$1" | head -c 129)"
echo "Started verifying stream registry database entry $knownHash."
if sreg_read_stream --checksum "$knownHash" --disallow-hash-pointer < "$1"; then
    if [[ -n "$fsckStatusFile" ]]; then
        numberExpected="$(<"$fsckStatusFile")"
        numberProcessedFile="$fsckStatusFile.done"
        if ! [[ -f "$numberProcessedFile" ]]; then
            numberProcessed="1"
        else
            numberProcessed="$(<"$numberProcessedFile")"
            numberProcessed=$(( numberProcessed + 1 ))
        fi
        echo "$numberProcessed" > "$numberProcessedFile"
        if [[ "$numberExpected" == "0" ]]; then
            numberExpected="-1"
        fi
        numberProcessedPercentage="$(printf "%.3f\n" "$(bc -l <<< "($numberProcessed / $numberExpected) * 100")")"
        echo "Verified stream registry database entry $knownHash: finished #$numberProcessed of $numberExpected ($numberProcessedPercentage%)"
    else
        echo "Verified stream registry database entry $knownHash."
    fi
    exit
else
    dbDir="${EmberLibrary:?}"/Futuramerlin\ Projects/Data/Stream\ Registry/Failed\ Fsck/
    mkdir -p "$dbDir"
    mv "$1" "$dbDir/"
    error-die "Error verifying stream registry database entry $knownHash! Marking entry as corrupted."
fi
