#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

reportResult() {
    [[ -d "$1" ]] || die "Result from running sregi_find_dir in $(pwd) is not a directory!"
    print "$(readlink -f "$1")"
    exit 0
}

reportDefault() {
    reportResult "/library/ember-library-2/Futuramerlin Projects/Data/Stream Registry/"
}

if [[ "$1" == "--sreg-dir" ]]; then
    shift
    if [[ -n "$1" ]]; then
        reportResult "$1"
    else
        if [[ "$2" != "--full-check" ]]; then
            reportDefault
        else
            shift
            shift
        fi
    fi
fi

if [[ -n "$1" ]]; then
    if [[ -d "$1" ]]; then
        cd "$1" || die "Could not cd to specified directory!"
    else
        cd "$(dirname "$1")" || die "Could not cd to directory of specified path!"
    fi
fi

while [[ "$(readlink -e .)" != "/" ]]; do
    [[ -d ".sreg" ]] && reportResult "$(readlink -e .sreg)"
    cd .. || die "Could not cd to enclosing directory!"
done

reportDefault
