#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

packPointerName="$1"
dbDir="${EmberLibrary:?}"/Futuramerlin\ Projects/Data/Stream\ Registry
hashFull="$(basename "$2")"
hashPatternMatch='^[\da-f]{128}$'
# $hashPatternMatch not quoted because that makes it "match literally rather than as a regex" (—SC2076)
if ! [[ "$hashFull" =~ $hashPatternMatch ]]; then
    # Ignore stray files in the LocalStore directory (e.g. .keep files)
    exit 0
fi
hashA="${hashFull:0:1}"
hashB="${hashFull:1:1}"
hashC="${hashFull:2:1}"
hashDir="$dbDir/$hashA/$hashB/$hashC"
dbFilePath="$hashDir/$hashFull"
if [[ -f "$dbFilePath" ]]; then
    if [[ "$(head -c 36 "$dbFilePath")" != "c39f8657-384b-438b-a5a2-eece17147589" ]]; then
        die "The item $dbFilePath does not appear to be a LocalStore pointer! This is most likely a bug in sreg. Aborting to avoid messing things up."
    fi
fi
# 2fa... is the remote bundle pointer type signature
printf "2fae2004-94bb-4aa8-a01a-fc44298efc2c\\n%s\\n%s" "$hashFull" "$(basename "$packPointerName")" > "$dbFilePath"
