#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"

temp="$(tempFile)"
wget 
say '45baff46-8db7-46f6-aad9-de5f713b02fe'
printf '%s\n' '45baff46-8db7-46f6-aad9-de5f713b02fe'
printf '%s\n' '45baff46-8db7-46f6-aad9-de5f713b02fe'
