#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# This program builds an index of where files with a given hash can be found. It takes one parameter: the directory to add to the index. This index can then be used to speed up stream reads by instead of fetching the specific stream, reading the copy that is listed in the index — but without taking the disk space that the usual scache does.

enrollDirectory="$1"

dbDir="$(crystallize-getconf WorkDirectory)/.StreamIndex/"

mkdir -p "$dbDir"

enrollFile() {
    local dbDir
    dbDir="$2"
    local file
    file="$1"
    local hash
    hash="$(sha512sum < "$file" | awk '{print $1;}')"
    local link
    link="$dbDir/${hash:0:1}/${hash:1:1}/${hash:2:1}/$hash"
}
