#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

sregDir=""
if [[ "$1" == "--sreg-dir" ]]; then
    shift
    sregDir="$1"
    shift
fi
sregDir="$(sregi_find_dir --sreg-dir "$sregDir" --full-check "${!#}")"

action="mount"
if [[ "$1" == "mount" ]]; then
    shift
elif [[ "$1" == "unmount" ]]; then
    action="unmount"
    shift
fi

case $action in
mount)
    root="$1"
    if [[ -z "$root" ]]; then
        root="$(crystallize-getconf SrfsDefaultRoot)"
        if [[ -z "$root" ]]; then
            root="$(crystallize-getconf EmberLibrary)"
        fi
    fi
    mountpoint="$2"
    if [[ -z "$mountpoint" ]]; then
        mountpoint="$(crystallize-getconf SrfsMountpoint)"
    fi
    mkdir -p "$mountpoint"
    ( sreg_fuse --sreg-dir "$sregDir" "$root" "$mountpoint" & ) # Double fork so sreg_fuse.py survives after srfs exits
    ;;
unmount)
    mountpoint="$1"
    if [[ -z "$mountpoint" ]]; then
        mountpoint="$(crystallize-getconf SrfsMountpoint)"
    fi
    umount "$mountpoint"
    ;;
*)
    echo "Unknown action."
    exit 1
    ;;
esac
