#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

action="$1"
mountpoint="$(crystallize-getconf SrfsMountpoint)"

if [[ -z "$action" ]]; then
    action="mount"
fi

case $action in
mount)
    mkdir -p "$mountpoint"
    root="$2"
    if [[ -z "$root" ]]; then
        root="$(crystallize-getconf SrfsDefaultRoot)"
        if [[ -z "$root" ]]; then
            root="$(crystallize-getconf EmberLibrary)"
        fi
    fi
    ( sreg_fuse_py "$root" "$mountpoint" & ) # Double fork so sreg_fuse.py survives after srfs exits
    ;;
unmount)
    umount "$mountpoint"
    ;;
*)
    echo "Unknown action."
    exit 1
    ;;
esac
