#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

((EUID)) && exec sudo -- "$0" "$@"
trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR

rsync -av --checksum --progress --no-i-r --ignore-existing "$1" "$2/"
rsync -av --checksum --progress --no-i-r --ignore-existing "$1" "$2/"
sregi_expand_pointers "$2/$(basename "$1")"
