#!/bin/bash
# Enroll the specified file(s) in the smallify-stream cache database
set -e
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
while [[ ! -z $1 ]]; do
    echo "Items remaining to precache: "
    echo "$@"
    fileToStash="$1"
    echo "Begun precaching $fileToStash."
    if [ -f "$fileToStash" ]; then
        smallify-stream --verbose < "$fileToStash"
    else
        sstream-dircache "$fileToStash" || warn "Failed precaching $fileToStash!"
    fi
    echo "Done precaching $fileToStash." || warn "Failed precaching $fileToStash!"
    shift
done
printf "\033c"
echo "Done precaching all items."
