#!/bin/bash
# Smallify the specified file(s) using the cache database
set -e
[ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
while [[ ! -z $1 ]]; do
    echo "Items remaining to smallify: "
    echo "$@"
    fileToStash="$1"
    echo "Begun smallify $fileToStash."
    if [ -f $fileToStash ]; then
        smallify-stream < "$fileToStash"
    else
        sstream-dircache < "$fileToStash"
    fi
    echo "Done precaching $fileToStash."
    shift
done
printf "\033c"
echo "Done precaching all items."
;;
