#!/bin/bash
# Verify the stream database
set -e
dbDir=/Ember\ Library/Futuramerlin\ Projects/Data/Stream\ Registry
checkFile() {
    knownHash="$1"
    recoveredHash="$(biggify-stream < "$1" | sha512sum)"
    
}
find "$dbDir" -type f -exec checkFile {} \;
